/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.getconvoy.api;

import com.getconvoy.client.ApiClient;
import com.getconvoy.client.ApiException;
import com.getconvoy.client.ApiResponse;
import com.getconvoy.client.Configuration;
import com.getconvoy.client.Pair;

import com.getconvoy.models.CreateEndpoint201Response;
import com.getconvoy.models.GetEndpoints200Response;
import com.getconvoy.models.GetProjects400Response;
import com.getconvoy.models.ModelsCreateEndpoint;
import com.getconvoy.models.ModelsExpireSecret;
import com.getconvoy.models.ModelsTestOAuth2Request;
import com.getconvoy.models.ModelsUpdateEndpoint;
import com.getconvoy.models.TestOAuth2Connection200Response;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class EndpointsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public EndpointsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public EndpointsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Activate endpoint
   * Activated an inactive endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @return CreateEndpoint201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEndpoint201Response activateEndpoint(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID) throws ApiException {
    return activateEndpoint(projectID, endpointID, null);
  }

  /**
   * Activate endpoint
   * Activated an inactive endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param headers Optional headers to include in the request
   * @return CreateEndpoint201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEndpoint201Response activateEndpoint(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateEndpoint201Response> localVarResponse = activateEndpointWithHttpInfo(projectID, endpointID, headers);
    return localVarResponse.getData();
  }

  /**
   * Activate endpoint
   * Activated an inactive endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @return ApiResponse&lt;CreateEndpoint201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEndpoint201Response> activateEndpointWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID) throws ApiException {
    return activateEndpointWithHttpInfo(projectID, endpointID, null);
  }

  /**
   * Activate endpoint
   * Activated an inactive endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateEndpoint201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEndpoint201Response> activateEndpointWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = activateEndpointRequestBuilder(projectID, endpointID, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("activateEndpoint", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateEndpoint201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateEndpoint201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateEndpoint201Response>() {});
        

        return new ApiResponse<CreateEndpoint201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder activateEndpointRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling activateEndpoint");
    }
    // verify the required parameter 'endpointID' is set
    if (endpointID == null) {
      throw new ApiException(400, "Missing the required parameter 'endpointID' when calling activateEndpoint");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/endpoints/{endpointID}/activate"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()))
        .replace("{endpointID}", ApiClient.urlEncode(endpointID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Create an endpoint
   * This endpoint creates an endpoint
   * @param projectID Project ID (required)
   * @param modelsCreateEndpoint Endpoint Details (required)
   * @return CreateEndpoint201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEndpoint201Response createEndpoint(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateEndpoint modelsCreateEndpoint) throws ApiException {
    return createEndpoint(projectID, modelsCreateEndpoint, null);
  }

  /**
   * Create an endpoint
   * This endpoint creates an endpoint
   * @param projectID Project ID (required)
   * @param modelsCreateEndpoint Endpoint Details (required)
   * @param headers Optional headers to include in the request
   * @return CreateEndpoint201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEndpoint201Response createEndpoint(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateEndpoint modelsCreateEndpoint, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateEndpoint201Response> localVarResponse = createEndpointWithHttpInfo(projectID, modelsCreateEndpoint, headers);
    return localVarResponse.getData();
  }

  /**
   * Create an endpoint
   * This endpoint creates an endpoint
   * @param projectID Project ID (required)
   * @param modelsCreateEndpoint Endpoint Details (required)
   * @return ApiResponse&lt;CreateEndpoint201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEndpoint201Response> createEndpointWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateEndpoint modelsCreateEndpoint) throws ApiException {
    return createEndpointWithHttpInfo(projectID, modelsCreateEndpoint, null);
  }

  /**
   * Create an endpoint
   * This endpoint creates an endpoint
   * @param projectID Project ID (required)
   * @param modelsCreateEndpoint Endpoint Details (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateEndpoint201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEndpoint201Response> createEndpointWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateEndpoint modelsCreateEndpoint, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createEndpointRequestBuilder(projectID, modelsCreateEndpoint, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createEndpoint", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateEndpoint201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateEndpoint201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateEndpoint201Response>() {});
        

        return new ApiResponse<CreateEndpoint201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createEndpointRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateEndpoint modelsCreateEndpoint, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling createEndpoint");
    }
    // verify the required parameter 'modelsCreateEndpoint' is set
    if (modelsCreateEndpoint == null) {
      throw new ApiException(400, "Missing the required parameter 'modelsCreateEndpoint' when calling createEndpoint");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/endpoints"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(modelsCreateEndpoint);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete endpoint
   * This endpoint deletes an endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @return GetProjects400Response
   * @throws ApiException if fails to make API call
   */
  public GetProjects400Response deleteEndpoint(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID) throws ApiException {
    return deleteEndpoint(projectID, endpointID, null);
  }

  /**
   * Delete endpoint
   * This endpoint deletes an endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param headers Optional headers to include in the request
   * @return GetProjects400Response
   * @throws ApiException if fails to make API call
   */
  public GetProjects400Response deleteEndpoint(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, Map<String, String> headers) throws ApiException {
    ApiResponse<GetProjects400Response> localVarResponse = deleteEndpointWithHttpInfo(projectID, endpointID, headers);
    return localVarResponse.getData();
  }

  /**
   * Delete endpoint
   * This endpoint deletes an endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @return ApiResponse&lt;GetProjects400Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetProjects400Response> deleteEndpointWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID) throws ApiException {
    return deleteEndpointWithHttpInfo(projectID, endpointID, null);
  }

  /**
   * Delete endpoint
   * This endpoint deletes an endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetProjects400Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetProjects400Response> deleteEndpointWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteEndpointRequestBuilder(projectID, endpointID, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteEndpoint", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetProjects400Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetProjects400Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetProjects400Response>() {});
        

        return new ApiResponse<GetProjects400Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteEndpointRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling deleteEndpoint");
    }
    // verify the required parameter 'endpointID' is set
    if (endpointID == null) {
      throw new ApiException(400, "Missing the required parameter 'endpointID' when calling deleteEndpoint");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/endpoints/{endpointID}"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()))
        .replace("{endpointID}", ApiClient.urlEncode(endpointID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Roll endpoint secret
   * This endpoint expires and re-generates the endpoint secret.
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param modelsExpireSecret Expire Secret Body Parameters (required)
   * @return CreateEndpoint201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEndpoint201Response expireSecret(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, @jakarta.annotation.Nonnull ModelsExpireSecret modelsExpireSecret) throws ApiException {
    return expireSecret(projectID, endpointID, modelsExpireSecret, null);
  }

  /**
   * Roll endpoint secret
   * This endpoint expires and re-generates the endpoint secret.
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param modelsExpireSecret Expire Secret Body Parameters (required)
   * @param headers Optional headers to include in the request
   * @return CreateEndpoint201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEndpoint201Response expireSecret(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, @jakarta.annotation.Nonnull ModelsExpireSecret modelsExpireSecret, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateEndpoint201Response> localVarResponse = expireSecretWithHttpInfo(projectID, endpointID, modelsExpireSecret, headers);
    return localVarResponse.getData();
  }

  /**
   * Roll endpoint secret
   * This endpoint expires and re-generates the endpoint secret.
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param modelsExpireSecret Expire Secret Body Parameters (required)
   * @return ApiResponse&lt;CreateEndpoint201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEndpoint201Response> expireSecretWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, @jakarta.annotation.Nonnull ModelsExpireSecret modelsExpireSecret) throws ApiException {
    return expireSecretWithHttpInfo(projectID, endpointID, modelsExpireSecret, null);
  }

  /**
   * Roll endpoint secret
   * This endpoint expires and re-generates the endpoint secret.
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param modelsExpireSecret Expire Secret Body Parameters (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateEndpoint201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEndpoint201Response> expireSecretWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, @jakarta.annotation.Nonnull ModelsExpireSecret modelsExpireSecret, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = expireSecretRequestBuilder(projectID, endpointID, modelsExpireSecret, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("expireSecret", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateEndpoint201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateEndpoint201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateEndpoint201Response>() {});
        

        return new ApiResponse<CreateEndpoint201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder expireSecretRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, @jakarta.annotation.Nonnull ModelsExpireSecret modelsExpireSecret, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling expireSecret");
    }
    // verify the required parameter 'endpointID' is set
    if (endpointID == null) {
      throw new ApiException(400, "Missing the required parameter 'endpointID' when calling expireSecret");
    }
    // verify the required parameter 'modelsExpireSecret' is set
    if (modelsExpireSecret == null) {
      throw new ApiException(400, "Missing the required parameter 'modelsExpireSecret' when calling expireSecret");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/endpoints/{endpointID}/expire_secret"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()))
        .replace("{endpointID}", ApiClient.urlEncode(endpointID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(modelsExpireSecret);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Retrieve endpoint
   * This endpoint fetches an endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @return CreateEndpoint201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEndpoint201Response getEndpoint(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID) throws ApiException {
    return getEndpoint(projectID, endpointID, null);
  }

  /**
   * Retrieve endpoint
   * This endpoint fetches an endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param headers Optional headers to include in the request
   * @return CreateEndpoint201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEndpoint201Response getEndpoint(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateEndpoint201Response> localVarResponse = getEndpointWithHttpInfo(projectID, endpointID, headers);
    return localVarResponse.getData();
  }

  /**
   * Retrieve endpoint
   * This endpoint fetches an endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @return ApiResponse&lt;CreateEndpoint201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEndpoint201Response> getEndpointWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID) throws ApiException {
    return getEndpointWithHttpInfo(projectID, endpointID, null);
  }

  /**
   * Retrieve endpoint
   * This endpoint fetches an endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateEndpoint201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEndpoint201Response> getEndpointWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEndpointRequestBuilder(projectID, endpointID, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEndpoint", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateEndpoint201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateEndpoint201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateEndpoint201Response>() {});
        

        return new ApiResponse<CreateEndpoint201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEndpointRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling getEndpoint");
    }
    // verify the required parameter 'endpointID' is set
    if (endpointID == null) {
      throw new ApiException(400, "Missing the required parameter 'endpointID' when calling getEndpoint");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/endpoints/{endpointID}"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()))
        .replace("{endpointID}", ApiClient.urlEncode(endpointID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all endpoints
   * This endpoint fetches an endpoints
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param ownerId The owner ID of the endpoint (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param q The name of the endpoint (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @return GetEndpoints200Response
   * @throws ApiException if fails to make API call
   */
  public GetEndpoints200Response getEndpoints(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable String ownerId, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String q, @jakarta.annotation.Nullable String sort) throws ApiException {
    return getEndpoints(projectID, direction, nextPageCursor, ownerId, perPage, prevPageCursor, q, sort, null);
  }

  /**
   * List all endpoints
   * This endpoint fetches an endpoints
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param ownerId The owner ID of the endpoint (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param q The name of the endpoint (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param headers Optional headers to include in the request
   * @return GetEndpoints200Response
   * @throws ApiException if fails to make API call
   */
  public GetEndpoints200Response getEndpoints(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable String ownerId, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String q, @jakarta.annotation.Nullable String sort, Map<String, String> headers) throws ApiException {
    ApiResponse<GetEndpoints200Response> localVarResponse = getEndpointsWithHttpInfo(projectID, direction, nextPageCursor, ownerId, perPage, prevPageCursor, q, sort, headers);
    return localVarResponse.getData();
  }

  /**
   * List all endpoints
   * This endpoint fetches an endpoints
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param ownerId The owner ID of the endpoint (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param q The name of the endpoint (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @return ApiResponse&lt;GetEndpoints200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetEndpoints200Response> getEndpointsWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable String ownerId, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String q, @jakarta.annotation.Nullable String sort) throws ApiException {
    return getEndpointsWithHttpInfo(projectID, direction, nextPageCursor, ownerId, perPage, prevPageCursor, q, sort, null);
  }

  /**
   * List all endpoints
   * This endpoint fetches an endpoints
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param ownerId The owner ID of the endpoint (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param q The name of the endpoint (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetEndpoints200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetEndpoints200Response> getEndpointsWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable String ownerId, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String q, @jakarta.annotation.Nullable String sort, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEndpointsRequestBuilder(projectID, direction, nextPageCursor, ownerId, perPage, prevPageCursor, q, sort, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEndpoints", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetEndpoints200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetEndpoints200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetEndpoints200Response>() {});
        

        return new ApiResponse<GetEndpoints200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEndpointsRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable String ownerId, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String q, @jakarta.annotation.Nullable String sort, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling getEndpoints");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/endpoints"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "direction";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("direction", direction));
    localVarQueryParameterBaseName = "next_page_cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("next_page_cursor", nextPageCursor));
    localVarQueryParameterBaseName = "ownerId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("ownerId", ownerId));
    localVarQueryParameterBaseName = "perPage";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("perPage", perPage));
    localVarQueryParameterBaseName = "prev_page_cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("prev_page_cursor", prevPageCursor));
    localVarQueryParameterBaseName = "q";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("q", q));
    localVarQueryParameterBaseName = "sort";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sort", sort));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Pause endpoint
   * Toggles an endpoint&#39;s status between active and paused states
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @return CreateEndpoint201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEndpoint201Response pauseEndpoint(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID) throws ApiException {
    return pauseEndpoint(projectID, endpointID, null);
  }

  /**
   * Pause endpoint
   * Toggles an endpoint&#39;s status between active and paused states
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param headers Optional headers to include in the request
   * @return CreateEndpoint201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEndpoint201Response pauseEndpoint(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateEndpoint201Response> localVarResponse = pauseEndpointWithHttpInfo(projectID, endpointID, headers);
    return localVarResponse.getData();
  }

  /**
   * Pause endpoint
   * Toggles an endpoint&#39;s status between active and paused states
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @return ApiResponse&lt;CreateEndpoint201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEndpoint201Response> pauseEndpointWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID) throws ApiException {
    return pauseEndpointWithHttpInfo(projectID, endpointID, null);
  }

  /**
   * Pause endpoint
   * Toggles an endpoint&#39;s status between active and paused states
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateEndpoint201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEndpoint201Response> pauseEndpointWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = pauseEndpointRequestBuilder(projectID, endpointID, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("pauseEndpoint", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateEndpoint201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateEndpoint201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateEndpoint201Response>() {});
        

        return new ApiResponse<CreateEndpoint201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder pauseEndpointRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling pauseEndpoint");
    }
    // verify the required parameter 'endpointID' is set
    if (endpointID == null) {
      throw new ApiException(400, "Missing the required parameter 'endpointID' when calling pauseEndpoint");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/endpoints/{endpointID}/pause"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()))
        .replace("{endpointID}", ApiClient.urlEncode(endpointID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Test OAuth2 connection
   * This endpoint tests the OAuth2 connection by attempting to exchange a token
   * @param projectID Project ID (required)
   * @param modelsTestOAuth2Request OAuth2 Configuration (required)
   * @return TestOAuth2Connection200Response
   * @throws ApiException if fails to make API call
   */
  public TestOAuth2Connection200Response testOAuth2Connection(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsTestOAuth2Request modelsTestOAuth2Request) throws ApiException {
    return testOAuth2Connection(projectID, modelsTestOAuth2Request, null);
  }

  /**
   * Test OAuth2 connection
   * This endpoint tests the OAuth2 connection by attempting to exchange a token
   * @param projectID Project ID (required)
   * @param modelsTestOAuth2Request OAuth2 Configuration (required)
   * @param headers Optional headers to include in the request
   * @return TestOAuth2Connection200Response
   * @throws ApiException if fails to make API call
   */
  public TestOAuth2Connection200Response testOAuth2Connection(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsTestOAuth2Request modelsTestOAuth2Request, Map<String, String> headers) throws ApiException {
    ApiResponse<TestOAuth2Connection200Response> localVarResponse = testOAuth2ConnectionWithHttpInfo(projectID, modelsTestOAuth2Request, headers);
    return localVarResponse.getData();
  }

  /**
   * Test OAuth2 connection
   * This endpoint tests the OAuth2 connection by attempting to exchange a token
   * @param projectID Project ID (required)
   * @param modelsTestOAuth2Request OAuth2 Configuration (required)
   * @return ApiResponse&lt;TestOAuth2Connection200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TestOAuth2Connection200Response> testOAuth2ConnectionWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsTestOAuth2Request modelsTestOAuth2Request) throws ApiException {
    return testOAuth2ConnectionWithHttpInfo(projectID, modelsTestOAuth2Request, null);
  }

  /**
   * Test OAuth2 connection
   * This endpoint tests the OAuth2 connection by attempting to exchange a token
   * @param projectID Project ID (required)
   * @param modelsTestOAuth2Request OAuth2 Configuration (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TestOAuth2Connection200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TestOAuth2Connection200Response> testOAuth2ConnectionWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsTestOAuth2Request modelsTestOAuth2Request, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = testOAuth2ConnectionRequestBuilder(projectID, modelsTestOAuth2Request, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("testOAuth2Connection", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<TestOAuth2Connection200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        TestOAuth2Connection200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TestOAuth2Connection200Response>() {});
        

        return new ApiResponse<TestOAuth2Connection200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder testOAuth2ConnectionRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsTestOAuth2Request modelsTestOAuth2Request, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling testOAuth2Connection");
    }
    // verify the required parameter 'modelsTestOAuth2Request' is set
    if (modelsTestOAuth2Request == null) {
      throw new ApiException(400, "Missing the required parameter 'modelsTestOAuth2Request' when calling testOAuth2Connection");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/endpoints/oauth2/test"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(modelsTestOAuth2Request);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update an endpoint
   * This endpoint updates an endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param modelsUpdateEndpoint Endpoint Details (required)
   * @return CreateEndpoint201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEndpoint201Response updateEndpoint(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, @jakarta.annotation.Nonnull ModelsUpdateEndpoint modelsUpdateEndpoint) throws ApiException {
    return updateEndpoint(projectID, endpointID, modelsUpdateEndpoint, null);
  }

  /**
   * Update an endpoint
   * This endpoint updates an endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param modelsUpdateEndpoint Endpoint Details (required)
   * @param headers Optional headers to include in the request
   * @return CreateEndpoint201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEndpoint201Response updateEndpoint(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, @jakarta.annotation.Nonnull ModelsUpdateEndpoint modelsUpdateEndpoint, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateEndpoint201Response> localVarResponse = updateEndpointWithHttpInfo(projectID, endpointID, modelsUpdateEndpoint, headers);
    return localVarResponse.getData();
  }

  /**
   * Update an endpoint
   * This endpoint updates an endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param modelsUpdateEndpoint Endpoint Details (required)
   * @return ApiResponse&lt;CreateEndpoint201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEndpoint201Response> updateEndpointWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, @jakarta.annotation.Nonnull ModelsUpdateEndpoint modelsUpdateEndpoint) throws ApiException {
    return updateEndpointWithHttpInfo(projectID, endpointID, modelsUpdateEndpoint, null);
  }

  /**
   * Update an endpoint
   * This endpoint updates an endpoint
   * @param projectID Project ID (required)
   * @param endpointID Endpoint ID (required)
   * @param modelsUpdateEndpoint Endpoint Details (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateEndpoint201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEndpoint201Response> updateEndpointWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, @jakarta.annotation.Nonnull ModelsUpdateEndpoint modelsUpdateEndpoint, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateEndpointRequestBuilder(projectID, endpointID, modelsUpdateEndpoint, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateEndpoint", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateEndpoint201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateEndpoint201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateEndpoint201Response>() {});
        

        return new ApiResponse<CreateEndpoint201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateEndpointRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String endpointID, @jakarta.annotation.Nonnull ModelsUpdateEndpoint modelsUpdateEndpoint, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling updateEndpoint");
    }
    // verify the required parameter 'endpointID' is set
    if (endpointID == null) {
      throw new ApiException(400, "Missing the required parameter 'endpointID' when calling updateEndpoint");
    }
    // verify the required parameter 'modelsUpdateEndpoint' is set
    if (modelsUpdateEndpoint == null) {
      throw new ApiException(400, "Missing the required parameter 'modelsUpdateEndpoint' when calling updateEndpoint");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/endpoints/{endpointID}"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()))
        .replace("{endpointID}", ApiClient.urlEncode(endpointID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(modelsUpdateEndpoint);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
