/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.getconvoy.api;

import com.getconvoy.client.ApiClient;
import com.getconvoy.client.ApiException;
import com.getconvoy.client.ApiResponse;
import com.getconvoy.client.Configuration;
import com.getconvoy.client.Pair;

import com.getconvoy.models.BatchReplayEvents200Response;
import com.getconvoy.models.CountAffectedEvents200Response;
import com.getconvoy.models.CreateBroadcastEvent201Response;
import com.getconvoy.models.GetEventsPaged200Response;
import com.getconvoy.models.GetProjects400Response;
import com.getconvoy.models.ModelsBroadcastEvent;
import com.getconvoy.models.ModelsCreateEvent;
import com.getconvoy.models.ModelsDynamicEvent;
import com.getconvoy.models.ModelsFanoutEvent;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class EventsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public EventsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public EventsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Batch replay events
   * This endpoint replays multiple events at once.
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endDate The end date (optional)
   * @param endpointId A list of endpoint ids to filter by (optional)
   * @param idempotencyKey IdempotencyKey to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param query Any arbitrary value to filter the events payload (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param sourceId A list of Source IDs to filter the events by. (optional)
   * @param startDate The start date (optional)
   * @return BatchReplayEvents200Response
   * @throws ApiException if fails to make API call
   */
  public BatchReplayEvents200Response batchReplayEvents(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate) throws ApiException {
    return batchReplayEvents(projectID, direction, endDate, endpointId, idempotencyKey, nextPageCursor, perPage, prevPageCursor, query, sort, sourceId, startDate, null);
  }

  /**
   * Batch replay events
   * This endpoint replays multiple events at once.
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endDate The end date (optional)
   * @param endpointId A list of endpoint ids to filter by (optional)
   * @param idempotencyKey IdempotencyKey to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param query Any arbitrary value to filter the events payload (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param sourceId A list of Source IDs to filter the events by. (optional)
   * @param startDate The start date (optional)
   * @param headers Optional headers to include in the request
   * @return BatchReplayEvents200Response
   * @throws ApiException if fails to make API call
   */
  public BatchReplayEvents200Response batchReplayEvents(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate, Map<String, String> headers) throws ApiException {
    ApiResponse<BatchReplayEvents200Response> localVarResponse = batchReplayEventsWithHttpInfo(projectID, direction, endDate, endpointId, idempotencyKey, nextPageCursor, perPage, prevPageCursor, query, sort, sourceId, startDate, headers);
    return localVarResponse.getData();
  }

  /**
   * Batch replay events
   * This endpoint replays multiple events at once.
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endDate The end date (optional)
   * @param endpointId A list of endpoint ids to filter by (optional)
   * @param idempotencyKey IdempotencyKey to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param query Any arbitrary value to filter the events payload (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param sourceId A list of Source IDs to filter the events by. (optional)
   * @param startDate The start date (optional)
   * @return ApiResponse&lt;BatchReplayEvents200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<BatchReplayEvents200Response> batchReplayEventsWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate) throws ApiException {
    return batchReplayEventsWithHttpInfo(projectID, direction, endDate, endpointId, idempotencyKey, nextPageCursor, perPage, prevPageCursor, query, sort, sourceId, startDate, null);
  }

  /**
   * Batch replay events
   * This endpoint replays multiple events at once.
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endDate The end date (optional)
   * @param endpointId A list of endpoint ids to filter by (optional)
   * @param idempotencyKey IdempotencyKey to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param query Any arbitrary value to filter the events payload (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param sourceId A list of Source IDs to filter the events by. (optional)
   * @param startDate The start date (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;BatchReplayEvents200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<BatchReplayEvents200Response> batchReplayEventsWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = batchReplayEventsRequestBuilder(projectID, direction, endDate, endpointId, idempotencyKey, nextPageCursor, perPage, prevPageCursor, query, sort, sourceId, startDate, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("batchReplayEvents", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<BatchReplayEvents200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        BatchReplayEvents200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<BatchReplayEvents200Response>() {});
        

        return new ApiResponse<BatchReplayEvents200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder batchReplayEventsRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling batchReplayEvents");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/events/batchreplay"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "direction";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("direction", direction));
    localVarQueryParameterBaseName = "endDate";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("endDate", endDate));
    localVarQueryParameterBaseName = "endpointId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("multi", "endpointId", endpointId));
    localVarQueryParameterBaseName = "idempotencyKey";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("idempotencyKey", idempotencyKey));
    localVarQueryParameterBaseName = "next_page_cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("next_page_cursor", nextPageCursor));
    localVarQueryParameterBaseName = "perPage";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("perPage", perPage));
    localVarQueryParameterBaseName = "prev_page_cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("prev_page_cursor", prevPageCursor));
    localVarQueryParameterBaseName = "query";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("query", query));
    localVarQueryParameterBaseName = "sort";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sort", sort));
    localVarQueryParameterBaseName = "sourceId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("multi", "sourceId", sourceId));
    localVarQueryParameterBaseName = "startDate";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("startDate", startDate));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Count events matching batch replay filters
   * This endpoint returns how many events would be affected by a batch replay with the given filters.
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endDate The end date (optional)
   * @param endpointId A list of endpoint ids to filter by (optional)
   * @param idempotencyKey IdempotencyKey to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param query Any arbitrary value to filter the events payload (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param sourceId A list of Source IDs to filter the events by. (optional)
   * @param startDate The start date (optional)
   * @return CountAffectedEvents200Response
   * @throws ApiException if fails to make API call
   */
  public CountAffectedEvents200Response countAffectedEvents(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate) throws ApiException {
    return countAffectedEvents(projectID, direction, endDate, endpointId, idempotencyKey, nextPageCursor, perPage, prevPageCursor, query, sort, sourceId, startDate, null);
  }

  /**
   * Count events matching batch replay filters
   * This endpoint returns how many events would be affected by a batch replay with the given filters.
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endDate The end date (optional)
   * @param endpointId A list of endpoint ids to filter by (optional)
   * @param idempotencyKey IdempotencyKey to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param query Any arbitrary value to filter the events payload (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param sourceId A list of Source IDs to filter the events by. (optional)
   * @param startDate The start date (optional)
   * @param headers Optional headers to include in the request
   * @return CountAffectedEvents200Response
   * @throws ApiException if fails to make API call
   */
  public CountAffectedEvents200Response countAffectedEvents(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate, Map<String, String> headers) throws ApiException {
    ApiResponse<CountAffectedEvents200Response> localVarResponse = countAffectedEventsWithHttpInfo(projectID, direction, endDate, endpointId, idempotencyKey, nextPageCursor, perPage, prevPageCursor, query, sort, sourceId, startDate, headers);
    return localVarResponse.getData();
  }

  /**
   * Count events matching batch replay filters
   * This endpoint returns how many events would be affected by a batch replay with the given filters.
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endDate The end date (optional)
   * @param endpointId A list of endpoint ids to filter by (optional)
   * @param idempotencyKey IdempotencyKey to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param query Any arbitrary value to filter the events payload (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param sourceId A list of Source IDs to filter the events by. (optional)
   * @param startDate The start date (optional)
   * @return ApiResponse&lt;CountAffectedEvents200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CountAffectedEvents200Response> countAffectedEventsWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate) throws ApiException {
    return countAffectedEventsWithHttpInfo(projectID, direction, endDate, endpointId, idempotencyKey, nextPageCursor, perPage, prevPageCursor, query, sort, sourceId, startDate, null);
  }

  /**
   * Count events matching batch replay filters
   * This endpoint returns how many events would be affected by a batch replay with the given filters.
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endDate The end date (optional)
   * @param endpointId A list of endpoint ids to filter by (optional)
   * @param idempotencyKey IdempotencyKey to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param query Any arbitrary value to filter the events payload (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param sourceId A list of Source IDs to filter the events by. (optional)
   * @param startDate The start date (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CountAffectedEvents200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CountAffectedEvents200Response> countAffectedEventsWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = countAffectedEventsRequestBuilder(projectID, direction, endDate, endpointId, idempotencyKey, nextPageCursor, perPage, prevPageCursor, query, sort, sourceId, startDate, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("countAffectedEvents", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CountAffectedEvents200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CountAffectedEvents200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CountAffectedEvents200Response>() {});
        

        return new ApiResponse<CountAffectedEvents200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder countAffectedEventsRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling countAffectedEvents");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/events/countbatchreplayevents"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "direction";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("direction", direction));
    localVarQueryParameterBaseName = "endDate";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("endDate", endDate));
    localVarQueryParameterBaseName = "endpointId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("multi", "endpointId", endpointId));
    localVarQueryParameterBaseName = "idempotencyKey";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("idempotencyKey", idempotencyKey));
    localVarQueryParameterBaseName = "next_page_cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("next_page_cursor", nextPageCursor));
    localVarQueryParameterBaseName = "perPage";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("perPage", perPage));
    localVarQueryParameterBaseName = "prev_page_cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("prev_page_cursor", prevPageCursor));
    localVarQueryParameterBaseName = "query";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("query", query));
    localVarQueryParameterBaseName = "sort";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sort", sort));
    localVarQueryParameterBaseName = "sourceId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("multi", "sourceId", sourceId));
    localVarQueryParameterBaseName = "startDate";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("startDate", startDate));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Create a broadcast event
   * This endpoint creates a event that is broadcast to every endpoint whose subscription matches the given event type.
   * @param projectID Project ID (required)
   * @param modelsBroadcastEvent Broadcast Event Details (required)
   * @return CreateBroadcastEvent201Response
   * @throws ApiException if fails to make API call
   */
  public CreateBroadcastEvent201Response createBroadcastEvent(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsBroadcastEvent modelsBroadcastEvent) throws ApiException {
    return createBroadcastEvent(projectID, modelsBroadcastEvent, null);
  }

  /**
   * Create a broadcast event
   * This endpoint creates a event that is broadcast to every endpoint whose subscription matches the given event type.
   * @param projectID Project ID (required)
   * @param modelsBroadcastEvent Broadcast Event Details (required)
   * @param headers Optional headers to include in the request
   * @return CreateBroadcastEvent201Response
   * @throws ApiException if fails to make API call
   */
  public CreateBroadcastEvent201Response createBroadcastEvent(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsBroadcastEvent modelsBroadcastEvent, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateBroadcastEvent201Response> localVarResponse = createBroadcastEventWithHttpInfo(projectID, modelsBroadcastEvent, headers);
    return localVarResponse.getData();
  }

  /**
   * Create a broadcast event
   * This endpoint creates a event that is broadcast to every endpoint whose subscription matches the given event type.
   * @param projectID Project ID (required)
   * @param modelsBroadcastEvent Broadcast Event Details (required)
   * @return ApiResponse&lt;CreateBroadcastEvent201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateBroadcastEvent201Response> createBroadcastEventWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsBroadcastEvent modelsBroadcastEvent) throws ApiException {
    return createBroadcastEventWithHttpInfo(projectID, modelsBroadcastEvent, null);
  }

  /**
   * Create a broadcast event
   * This endpoint creates a event that is broadcast to every endpoint whose subscription matches the given event type.
   * @param projectID Project ID (required)
   * @param modelsBroadcastEvent Broadcast Event Details (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateBroadcastEvent201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateBroadcastEvent201Response> createBroadcastEventWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsBroadcastEvent modelsBroadcastEvent, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createBroadcastEventRequestBuilder(projectID, modelsBroadcastEvent, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createBroadcastEvent", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateBroadcastEvent201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateBroadcastEvent201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateBroadcastEvent201Response>() {});
        

        return new ApiResponse<CreateBroadcastEvent201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createBroadcastEventRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsBroadcastEvent modelsBroadcastEvent, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling createBroadcastEvent");
    }
    // verify the required parameter 'modelsBroadcastEvent' is set
    if (modelsBroadcastEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'modelsBroadcastEvent' when calling createBroadcastEvent");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/events/broadcast"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(modelsBroadcastEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Dynamic Events
   * This endpoint does not require creating endpoint and subscriptions ahead of time. Instead, you supply the endpoint and the payload, and Convoy delivers the events
   * @param projectID Project ID (required)
   * @param modelsDynamicEvent Event Details (required)
   * @return GetProjects400Response
   * @throws ApiException if fails to make API call
   */
  public GetProjects400Response createDynamicEvent(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsDynamicEvent modelsDynamicEvent) throws ApiException {
    return createDynamicEvent(projectID, modelsDynamicEvent, null);
  }

  /**
   * Dynamic Events
   * This endpoint does not require creating endpoint and subscriptions ahead of time. Instead, you supply the endpoint and the payload, and Convoy delivers the events
   * @param projectID Project ID (required)
   * @param modelsDynamicEvent Event Details (required)
   * @param headers Optional headers to include in the request
   * @return GetProjects400Response
   * @throws ApiException if fails to make API call
   */
  public GetProjects400Response createDynamicEvent(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsDynamicEvent modelsDynamicEvent, Map<String, String> headers) throws ApiException {
    ApiResponse<GetProjects400Response> localVarResponse = createDynamicEventWithHttpInfo(projectID, modelsDynamicEvent, headers);
    return localVarResponse.getData();
  }

  /**
   * Dynamic Events
   * This endpoint does not require creating endpoint and subscriptions ahead of time. Instead, you supply the endpoint and the payload, and Convoy delivers the events
   * @param projectID Project ID (required)
   * @param modelsDynamicEvent Event Details (required)
   * @return ApiResponse&lt;GetProjects400Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetProjects400Response> createDynamicEventWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsDynamicEvent modelsDynamicEvent) throws ApiException {
    return createDynamicEventWithHttpInfo(projectID, modelsDynamicEvent, null);
  }

  /**
   * Dynamic Events
   * This endpoint does not require creating endpoint and subscriptions ahead of time. Instead, you supply the endpoint and the payload, and Convoy delivers the events
   * @param projectID Project ID (required)
   * @param modelsDynamicEvent Event Details (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetProjects400Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetProjects400Response> createDynamicEventWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsDynamicEvent modelsDynamicEvent, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createDynamicEventRequestBuilder(projectID, modelsDynamicEvent, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createDynamicEvent", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetProjects400Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetProjects400Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetProjects400Response>() {});
        

        return new ApiResponse<GetProjects400Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createDynamicEventRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsDynamicEvent modelsDynamicEvent, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling createDynamicEvent");
    }
    // verify the required parameter 'modelsDynamicEvent' is set
    if (modelsDynamicEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'modelsDynamicEvent' when calling createDynamicEvent");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/events/dynamic"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(modelsDynamicEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Create an event
   * This endpoint creates an endpoint event
   * @param projectID Project ID (required)
   * @param modelsCreateEvent Event Details (required)
   * @return GetProjects400Response
   * @throws ApiException if fails to make API call
   */
  public GetProjects400Response createEndpointEvent(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateEvent modelsCreateEvent) throws ApiException {
    return createEndpointEvent(projectID, modelsCreateEvent, null);
  }

  /**
   * Create an event
   * This endpoint creates an endpoint event
   * @param projectID Project ID (required)
   * @param modelsCreateEvent Event Details (required)
   * @param headers Optional headers to include in the request
   * @return GetProjects400Response
   * @throws ApiException if fails to make API call
   */
  public GetProjects400Response createEndpointEvent(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateEvent modelsCreateEvent, Map<String, String> headers) throws ApiException {
    ApiResponse<GetProjects400Response> localVarResponse = createEndpointEventWithHttpInfo(projectID, modelsCreateEvent, headers);
    return localVarResponse.getData();
  }

  /**
   * Create an event
   * This endpoint creates an endpoint event
   * @param projectID Project ID (required)
   * @param modelsCreateEvent Event Details (required)
   * @return ApiResponse&lt;GetProjects400Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetProjects400Response> createEndpointEventWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateEvent modelsCreateEvent) throws ApiException {
    return createEndpointEventWithHttpInfo(projectID, modelsCreateEvent, null);
  }

  /**
   * Create an event
   * This endpoint creates an endpoint event
   * @param projectID Project ID (required)
   * @param modelsCreateEvent Event Details (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetProjects400Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetProjects400Response> createEndpointEventWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateEvent modelsCreateEvent, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createEndpointEventRequestBuilder(projectID, modelsCreateEvent, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createEndpointEvent", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetProjects400Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetProjects400Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetProjects400Response>() {});
        

        return new ApiResponse<GetProjects400Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createEndpointEventRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateEvent modelsCreateEvent, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling createEndpointEvent");
    }
    // verify the required parameter 'modelsCreateEvent' is set
    if (modelsCreateEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'modelsCreateEvent' when calling createEndpointEvent");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/events"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(modelsCreateEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Fan out an event
   * This endpoint uses the owner_id to fan out an event to multiple endpoints.
   * @param projectID Project ID (required)
   * @param modelsFanoutEvent Event Details (required)
   * @return GetProjects400Response
   * @throws ApiException if fails to make API call
   */
  public GetProjects400Response createEndpointFanoutEvent(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFanoutEvent modelsFanoutEvent) throws ApiException {
    return createEndpointFanoutEvent(projectID, modelsFanoutEvent, null);
  }

  /**
   * Fan out an event
   * This endpoint uses the owner_id to fan out an event to multiple endpoints.
   * @param projectID Project ID (required)
   * @param modelsFanoutEvent Event Details (required)
   * @param headers Optional headers to include in the request
   * @return GetProjects400Response
   * @throws ApiException if fails to make API call
   */
  public GetProjects400Response createEndpointFanoutEvent(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFanoutEvent modelsFanoutEvent, Map<String, String> headers) throws ApiException {
    ApiResponse<GetProjects400Response> localVarResponse = createEndpointFanoutEventWithHttpInfo(projectID, modelsFanoutEvent, headers);
    return localVarResponse.getData();
  }

  /**
   * Fan out an event
   * This endpoint uses the owner_id to fan out an event to multiple endpoints.
   * @param projectID Project ID (required)
   * @param modelsFanoutEvent Event Details (required)
   * @return ApiResponse&lt;GetProjects400Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetProjects400Response> createEndpointFanoutEventWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFanoutEvent modelsFanoutEvent) throws ApiException {
    return createEndpointFanoutEventWithHttpInfo(projectID, modelsFanoutEvent, null);
  }

  /**
   * Fan out an event
   * This endpoint uses the owner_id to fan out an event to multiple endpoints.
   * @param projectID Project ID (required)
   * @param modelsFanoutEvent Event Details (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetProjects400Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetProjects400Response> createEndpointFanoutEventWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFanoutEvent modelsFanoutEvent, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createEndpointFanoutEventRequestBuilder(projectID, modelsFanoutEvent, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createEndpointFanoutEvent", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetProjects400Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetProjects400Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetProjects400Response>() {});
        

        return new ApiResponse<GetProjects400Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createEndpointFanoutEventRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFanoutEvent modelsFanoutEvent, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling createEndpointFanoutEvent");
    }
    // verify the required parameter 'modelsFanoutEvent' is set
    if (modelsFanoutEvent == null) {
      throw new ApiException(400, "Missing the required parameter 'modelsFanoutEvent' when calling createEndpointFanoutEvent");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/events/fanout"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(modelsFanoutEvent);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Retrieve an event
   * This endpoint retrieves an event
   * @param projectID Project ID (required)
   * @param eventID event id (required)
   * @return CreateBroadcastEvent201Response
   * @throws ApiException if fails to make API call
   */
  public CreateBroadcastEvent201Response getEndpointEvent(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String eventID) throws ApiException {
    return getEndpointEvent(projectID, eventID, null);
  }

  /**
   * Retrieve an event
   * This endpoint retrieves an event
   * @param projectID Project ID (required)
   * @param eventID event id (required)
   * @param headers Optional headers to include in the request
   * @return CreateBroadcastEvent201Response
   * @throws ApiException if fails to make API call
   */
  public CreateBroadcastEvent201Response getEndpointEvent(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String eventID, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateBroadcastEvent201Response> localVarResponse = getEndpointEventWithHttpInfo(projectID, eventID, headers);
    return localVarResponse.getData();
  }

  /**
   * Retrieve an event
   * This endpoint retrieves an event
   * @param projectID Project ID (required)
   * @param eventID event id (required)
   * @return ApiResponse&lt;CreateBroadcastEvent201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateBroadcastEvent201Response> getEndpointEventWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String eventID) throws ApiException {
    return getEndpointEventWithHttpInfo(projectID, eventID, null);
  }

  /**
   * Retrieve an event
   * This endpoint retrieves an event
   * @param projectID Project ID (required)
   * @param eventID event id (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateBroadcastEvent201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateBroadcastEvent201Response> getEndpointEventWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String eventID, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEndpointEventRequestBuilder(projectID, eventID, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEndpointEvent", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateBroadcastEvent201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateBroadcastEvent201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateBroadcastEvent201Response>() {});
        

        return new ApiResponse<CreateBroadcastEvent201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEndpointEventRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String eventID, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling getEndpointEvent");
    }
    // verify the required parameter 'eventID' is set
    if (eventID == null) {
      throw new ApiException(400, "Missing the required parameter 'eventID' when calling getEndpointEvent");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/events/{eventID}"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()))
        .replace("{eventID}", ApiClient.urlEncode(eventID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all events
   * This endpoint fetches app events with pagination
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endDate The end date (optional)
   * @param endpointId A list of endpoint ids to filter by (optional)
   * @param idempotencyKey IdempotencyKey to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param query Any arbitrary value to filter the events payload (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param sourceId A list of Source IDs to filter the events by. (optional)
   * @param startDate The start date (optional)
   * @return GetEventsPaged200Response
   * @throws ApiException if fails to make API call
   */
  public GetEventsPaged200Response getEventsPaged(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate) throws ApiException {
    return getEventsPaged(projectID, direction, endDate, endpointId, idempotencyKey, nextPageCursor, perPage, prevPageCursor, query, sort, sourceId, startDate, null);
  }

  /**
   * List all events
   * This endpoint fetches app events with pagination
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endDate The end date (optional)
   * @param endpointId A list of endpoint ids to filter by (optional)
   * @param idempotencyKey IdempotencyKey to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param query Any arbitrary value to filter the events payload (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param sourceId A list of Source IDs to filter the events by. (optional)
   * @param startDate The start date (optional)
   * @param headers Optional headers to include in the request
   * @return GetEventsPaged200Response
   * @throws ApiException if fails to make API call
   */
  public GetEventsPaged200Response getEventsPaged(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate, Map<String, String> headers) throws ApiException {
    ApiResponse<GetEventsPaged200Response> localVarResponse = getEventsPagedWithHttpInfo(projectID, direction, endDate, endpointId, idempotencyKey, nextPageCursor, perPage, prevPageCursor, query, sort, sourceId, startDate, headers);
    return localVarResponse.getData();
  }

  /**
   * List all events
   * This endpoint fetches app events with pagination
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endDate The end date (optional)
   * @param endpointId A list of endpoint ids to filter by (optional)
   * @param idempotencyKey IdempotencyKey to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param query Any arbitrary value to filter the events payload (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param sourceId A list of Source IDs to filter the events by. (optional)
   * @param startDate The start date (optional)
   * @return ApiResponse&lt;GetEventsPaged200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetEventsPaged200Response> getEventsPagedWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate) throws ApiException {
    return getEventsPagedWithHttpInfo(projectID, direction, endDate, endpointId, idempotencyKey, nextPageCursor, perPage, prevPageCursor, query, sort, sourceId, startDate, null);
  }

  /**
   * List all events
   * This endpoint fetches app events with pagination
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endDate The end date (optional)
   * @param endpointId A list of endpoint ids to filter by (optional)
   * @param idempotencyKey IdempotencyKey to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param query Any arbitrary value to filter the events payload (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param sourceId A list of Source IDs to filter the events by. (optional)
   * @param startDate The start date (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetEventsPaged200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetEventsPaged200Response> getEventsPagedWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEventsPagedRequestBuilder(projectID, direction, endDate, endpointId, idempotencyKey, nextPageCursor, perPage, prevPageCursor, query, sort, sourceId, startDate, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEventsPaged", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetEventsPaged200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetEventsPaged200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetEventsPaged200Response>() {});
        

        return new ApiResponse<GetEventsPaged200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEventsPagedRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable String endDate, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String idempotencyKey, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String query, @jakarta.annotation.Nullable String sort, @jakarta.annotation.Nullable List<String> sourceId, @jakarta.annotation.Nullable String startDate, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling getEventsPaged");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/events"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "direction";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("direction", direction));
    localVarQueryParameterBaseName = "endDate";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("endDate", endDate));
    localVarQueryParameterBaseName = "endpointId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("multi", "endpointId", endpointId));
    localVarQueryParameterBaseName = "idempotencyKey";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("idempotencyKey", idempotencyKey));
    localVarQueryParameterBaseName = "next_page_cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("next_page_cursor", nextPageCursor));
    localVarQueryParameterBaseName = "perPage";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("perPage", perPage));
    localVarQueryParameterBaseName = "prev_page_cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("prev_page_cursor", prevPageCursor));
    localVarQueryParameterBaseName = "query";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("query", query));
    localVarQueryParameterBaseName = "sort";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sort", sort));
    localVarQueryParameterBaseName = "sourceId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("multi", "sourceId", sourceId));
    localVarQueryParameterBaseName = "startDate";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("startDate", startDate));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Replay event
   * This endpoint replays an event afresh assuming it is a new event.
   * @param projectID Project ID (required)
   * @param eventID event id (required)
   * @return CreateBroadcastEvent201Response
   * @throws ApiException if fails to make API call
   */
  public CreateBroadcastEvent201Response replayEndpointEvent(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String eventID) throws ApiException {
    return replayEndpointEvent(projectID, eventID, null);
  }

  /**
   * Replay event
   * This endpoint replays an event afresh assuming it is a new event.
   * @param projectID Project ID (required)
   * @param eventID event id (required)
   * @param headers Optional headers to include in the request
   * @return CreateBroadcastEvent201Response
   * @throws ApiException if fails to make API call
   */
  public CreateBroadcastEvent201Response replayEndpointEvent(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String eventID, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateBroadcastEvent201Response> localVarResponse = replayEndpointEventWithHttpInfo(projectID, eventID, headers);
    return localVarResponse.getData();
  }

  /**
   * Replay event
   * This endpoint replays an event afresh assuming it is a new event.
   * @param projectID Project ID (required)
   * @param eventID event id (required)
   * @return ApiResponse&lt;CreateBroadcastEvent201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateBroadcastEvent201Response> replayEndpointEventWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String eventID) throws ApiException {
    return replayEndpointEventWithHttpInfo(projectID, eventID, null);
  }

  /**
   * Replay event
   * This endpoint replays an event afresh assuming it is a new event.
   * @param projectID Project ID (required)
   * @param eventID event id (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateBroadcastEvent201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateBroadcastEvent201Response> replayEndpointEventWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String eventID, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = replayEndpointEventRequestBuilder(projectID, eventID, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("replayEndpointEvent", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateBroadcastEvent201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateBroadcastEvent201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateBroadcastEvent201Response>() {});
        

        return new ApiResponse<CreateBroadcastEvent201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder replayEndpointEventRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String eventID, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling replayEndpointEvent");
    }
    // verify the required parameter 'eventID' is set
    if (eventID == null) {
      throw new ApiException(400, "Missing the required parameter 'eventID' when calling replayEndpointEvent");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/events/{eventID}/replay"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()))
        .replace("{eventID}", ApiClient.urlEncode(eventID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
