/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.getconvoy.api;

import com.getconvoy.client.ApiClient;
import com.getconvoy.client.ApiException;
import com.getconvoy.client.ApiResponse;
import com.getconvoy.client.Configuration;
import com.getconvoy.client.Pair;

import com.getconvoy.models.CreateSubscription201Response;
import com.getconvoy.models.GetProjects400Response;
import com.getconvoy.models.GetSubscriptions200Response;
import com.getconvoy.models.ModelsCreateSubscription;
import com.getconvoy.models.ModelsFunctionRequest;
import com.getconvoy.models.ModelsTestFilter;
import com.getconvoy.models.ModelsUpdateSubscription;
import com.getconvoy.models.TestSubscriptionFilter200Response;
import com.getconvoy.models.V1ProjectsProjectIDSourcesTestFunctionPost200Response;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class SubscriptionsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public SubscriptionsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public SubscriptionsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create a subscription
   * This endpoint creates a subscriptions
   * @param projectID Project ID (required)
   * @param modelsCreateSubscription Subscription details (required)
   * @return CreateSubscription201Response
   * @throws ApiException if fails to make API call
   */
  public CreateSubscription201Response createSubscription(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateSubscription modelsCreateSubscription) throws ApiException {
    return createSubscription(projectID, modelsCreateSubscription, null);
  }

  /**
   * Create a subscription
   * This endpoint creates a subscriptions
   * @param projectID Project ID (required)
   * @param modelsCreateSubscription Subscription details (required)
   * @param headers Optional headers to include in the request
   * @return CreateSubscription201Response
   * @throws ApiException if fails to make API call
   */
  public CreateSubscription201Response createSubscription(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateSubscription modelsCreateSubscription, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateSubscription201Response> localVarResponse = createSubscriptionWithHttpInfo(projectID, modelsCreateSubscription, headers);
    return localVarResponse.getData();
  }

  /**
   * Create a subscription
   * This endpoint creates a subscriptions
   * @param projectID Project ID (required)
   * @param modelsCreateSubscription Subscription details (required)
   * @return ApiResponse&lt;CreateSubscription201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateSubscription201Response> createSubscriptionWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateSubscription modelsCreateSubscription) throws ApiException {
    return createSubscriptionWithHttpInfo(projectID, modelsCreateSubscription, null);
  }

  /**
   * Create a subscription
   * This endpoint creates a subscriptions
   * @param projectID Project ID (required)
   * @param modelsCreateSubscription Subscription details (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateSubscription201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateSubscription201Response> createSubscriptionWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateSubscription modelsCreateSubscription, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createSubscriptionRequestBuilder(projectID, modelsCreateSubscription, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createSubscription", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateSubscription201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateSubscription201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateSubscription201Response>() {});
        

        return new ApiResponse<CreateSubscription201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createSubscriptionRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsCreateSubscription modelsCreateSubscription, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling createSubscription");
    }
    // verify the required parameter 'modelsCreateSubscription' is set
    if (modelsCreateSubscription == null) {
      throw new ApiException(400, "Missing the required parameter 'modelsCreateSubscription' when calling createSubscription");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/subscriptions"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(modelsCreateSubscription);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete subscription
   * This endpoint deletes a subscription
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @return GetProjects400Response
   * @throws ApiException if fails to make API call
   */
  public GetProjects400Response deleteSubscription(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID) throws ApiException {
    return deleteSubscription(projectID, subscriptionID, null);
  }

  /**
   * Delete subscription
   * This endpoint deletes a subscription
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @param headers Optional headers to include in the request
   * @return GetProjects400Response
   * @throws ApiException if fails to make API call
   */
  public GetProjects400Response deleteSubscription(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID, Map<String, String> headers) throws ApiException {
    ApiResponse<GetProjects400Response> localVarResponse = deleteSubscriptionWithHttpInfo(projectID, subscriptionID, headers);
    return localVarResponse.getData();
  }

  /**
   * Delete subscription
   * This endpoint deletes a subscription
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @return ApiResponse&lt;GetProjects400Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetProjects400Response> deleteSubscriptionWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID) throws ApiException {
    return deleteSubscriptionWithHttpInfo(projectID, subscriptionID, null);
  }

  /**
   * Delete subscription
   * This endpoint deletes a subscription
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetProjects400Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetProjects400Response> deleteSubscriptionWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteSubscriptionRequestBuilder(projectID, subscriptionID, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteSubscription", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetProjects400Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetProjects400Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetProjects400Response>() {});
        

        return new ApiResponse<GetProjects400Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteSubscriptionRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling deleteSubscription");
    }
    // verify the required parameter 'subscriptionID' is set
    if (subscriptionID == null) {
      throw new ApiException(400, "Missing the required parameter 'subscriptionID' when calling deleteSubscription");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/subscriptions/{subscriptionID}"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()))
        .replace("{subscriptionID}", ApiClient.urlEncode(subscriptionID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Retrieve a subscription
   * This endpoint retrieves a single subscription
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @return CreateSubscription201Response
   * @throws ApiException if fails to make API call
   */
  public CreateSubscription201Response getSubscription(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID) throws ApiException {
    return getSubscription(projectID, subscriptionID, null);
  }

  /**
   * Retrieve a subscription
   * This endpoint retrieves a single subscription
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @param headers Optional headers to include in the request
   * @return CreateSubscription201Response
   * @throws ApiException if fails to make API call
   */
  public CreateSubscription201Response getSubscription(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateSubscription201Response> localVarResponse = getSubscriptionWithHttpInfo(projectID, subscriptionID, headers);
    return localVarResponse.getData();
  }

  /**
   * Retrieve a subscription
   * This endpoint retrieves a single subscription
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @return ApiResponse&lt;CreateSubscription201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateSubscription201Response> getSubscriptionWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID) throws ApiException {
    return getSubscriptionWithHttpInfo(projectID, subscriptionID, null);
  }

  /**
   * Retrieve a subscription
   * This endpoint retrieves a single subscription
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateSubscription201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateSubscription201Response> getSubscriptionWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getSubscriptionRequestBuilder(projectID, subscriptionID, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getSubscription", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateSubscription201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateSubscription201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateSubscription201Response>() {});
        

        return new ApiResponse<CreateSubscription201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getSubscriptionRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling getSubscription");
    }
    // verify the required parameter 'subscriptionID' is set
    if (subscriptionID == null) {
      throw new ApiException(400, "Missing the required parameter 'subscriptionID' when calling getSubscription");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/subscriptions/{subscriptionID}"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()))
        .replace("{subscriptionID}", ApiClient.urlEncode(subscriptionID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all subscriptions
   * This endpoint fetches all the subscriptions
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endpointId A list of endpointIDs to filter by (optional)
   * @param name Subscription name to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @return GetSubscriptions200Response
   * @throws ApiException if fails to make API call
   */
  public GetSubscriptions200Response getSubscriptions(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String name, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String sort) throws ApiException {
    return getSubscriptions(projectID, direction, endpointId, name, nextPageCursor, perPage, prevPageCursor, sort, null);
  }

  /**
   * List all subscriptions
   * This endpoint fetches all the subscriptions
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endpointId A list of endpointIDs to filter by (optional)
   * @param name Subscription name to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param headers Optional headers to include in the request
   * @return GetSubscriptions200Response
   * @throws ApiException if fails to make API call
   */
  public GetSubscriptions200Response getSubscriptions(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String name, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String sort, Map<String, String> headers) throws ApiException {
    ApiResponse<GetSubscriptions200Response> localVarResponse = getSubscriptionsWithHttpInfo(projectID, direction, endpointId, name, nextPageCursor, perPage, prevPageCursor, sort, headers);
    return localVarResponse.getData();
  }

  /**
   * List all subscriptions
   * This endpoint fetches all the subscriptions
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endpointId A list of endpointIDs to filter by (optional)
   * @param name Subscription name to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @return ApiResponse&lt;GetSubscriptions200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetSubscriptions200Response> getSubscriptionsWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String name, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String sort) throws ApiException {
    return getSubscriptionsWithHttpInfo(projectID, direction, endpointId, name, nextPageCursor, perPage, prevPageCursor, sort, null);
  }

  /**
   * List all subscriptions
   * This endpoint fetches all the subscriptions
   * @param projectID Project ID (required)
   * @param direction  (optional)
   * @param endpointId A list of endpointIDs to filter by (optional)
   * @param name Subscription name to filter by (optional)
   * @param nextPageCursor A pagination cursor to fetch the next page of a list (optional)
   * @param perPage The number of items to return per page (optional)
   * @param prevPageCursor A pagination cursor to fetch the previous page of a list (optional)
   * @param sort Sort order, values are &#x60;ASC&#x60; or &#x60;DESC&#x60;, defaults to &#x60;DESC&#x60; (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetSubscriptions200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetSubscriptions200Response> getSubscriptionsWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String name, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String sort, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getSubscriptionsRequestBuilder(projectID, direction, endpointId, name, nextPageCursor, perPage, prevPageCursor, sort, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getSubscriptions", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetSubscriptions200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetSubscriptions200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetSubscriptions200Response>() {});
        

        return new ApiResponse<GetSubscriptions200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getSubscriptionsRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nullable String direction, @jakarta.annotation.Nullable List<String> endpointId, @jakarta.annotation.Nullable String name, @jakarta.annotation.Nullable String nextPageCursor, @jakarta.annotation.Nullable Integer perPage, @jakarta.annotation.Nullable String prevPageCursor, @jakarta.annotation.Nullable String sort, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling getSubscriptions");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/subscriptions"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "direction";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("direction", direction));
    localVarQueryParameterBaseName = "endpointId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("multi", "endpointId", endpointId));
    localVarQueryParameterBaseName = "name";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("name", name));
    localVarQueryParameterBaseName = "next_page_cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("next_page_cursor", nextPageCursor));
    localVarQueryParameterBaseName = "perPage";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("perPage", perPage));
    localVarQueryParameterBaseName = "prev_page_cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("prev_page_cursor", prevPageCursor));
    localVarQueryParameterBaseName = "sort";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sort", sort));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Validate subscription filter
   * This endpoint validates that a filter will match a certain payload structure.
   * @param projectID Project ID (required)
   * @param modelsTestFilter Filter Details (required)
   * @return TestSubscriptionFilter200Response
   * @throws ApiException if fails to make API call
   */
  public TestSubscriptionFilter200Response testSubscriptionFilter(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsTestFilter modelsTestFilter) throws ApiException {
    return testSubscriptionFilter(projectID, modelsTestFilter, null);
  }

  /**
   * Validate subscription filter
   * This endpoint validates that a filter will match a certain payload structure.
   * @param projectID Project ID (required)
   * @param modelsTestFilter Filter Details (required)
   * @param headers Optional headers to include in the request
   * @return TestSubscriptionFilter200Response
   * @throws ApiException if fails to make API call
   */
  public TestSubscriptionFilter200Response testSubscriptionFilter(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsTestFilter modelsTestFilter, Map<String, String> headers) throws ApiException {
    ApiResponse<TestSubscriptionFilter200Response> localVarResponse = testSubscriptionFilterWithHttpInfo(projectID, modelsTestFilter, headers);
    return localVarResponse.getData();
  }

  /**
   * Validate subscription filter
   * This endpoint validates that a filter will match a certain payload structure.
   * @param projectID Project ID (required)
   * @param modelsTestFilter Filter Details (required)
   * @return ApiResponse&lt;TestSubscriptionFilter200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TestSubscriptionFilter200Response> testSubscriptionFilterWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsTestFilter modelsTestFilter) throws ApiException {
    return testSubscriptionFilterWithHttpInfo(projectID, modelsTestFilter, null);
  }

  /**
   * Validate subscription filter
   * This endpoint validates that a filter will match a certain payload structure.
   * @param projectID Project ID (required)
   * @param modelsTestFilter Filter Details (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TestSubscriptionFilter200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TestSubscriptionFilter200Response> testSubscriptionFilterWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsTestFilter modelsTestFilter, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = testSubscriptionFilterRequestBuilder(projectID, modelsTestFilter, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("testSubscriptionFilter", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<TestSubscriptionFilter200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        TestSubscriptionFilter200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TestSubscriptionFilter200Response>() {});
        

        return new ApiResponse<TestSubscriptionFilter200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder testSubscriptionFilterRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsTestFilter modelsTestFilter, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling testSubscriptionFilter");
    }
    // verify the required parameter 'modelsTestFilter' is set
    if (modelsTestFilter == null) {
      throw new ApiException(400, "Missing the required parameter 'modelsTestFilter' when calling testSubscriptionFilter");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/subscriptions/test_filter"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(modelsTestFilter);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Test a subscription function
   * This endpoint test runs a transform function against a payload.
   * @param projectID Project ID (required)
   * @param modelsFunctionRequest Function Details (required)
   * @return V1ProjectsProjectIDSourcesTestFunctionPost200Response
   * @throws ApiException if fails to make API call
   */
  public V1ProjectsProjectIDSourcesTestFunctionPost200Response testSubscriptionFunction(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFunctionRequest modelsFunctionRequest) throws ApiException {
    return testSubscriptionFunction(projectID, modelsFunctionRequest, null);
  }

  /**
   * Test a subscription function
   * This endpoint test runs a transform function against a payload.
   * @param projectID Project ID (required)
   * @param modelsFunctionRequest Function Details (required)
   * @param headers Optional headers to include in the request
   * @return V1ProjectsProjectIDSourcesTestFunctionPost200Response
   * @throws ApiException if fails to make API call
   */
  public V1ProjectsProjectIDSourcesTestFunctionPost200Response testSubscriptionFunction(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFunctionRequest modelsFunctionRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<V1ProjectsProjectIDSourcesTestFunctionPost200Response> localVarResponse = testSubscriptionFunctionWithHttpInfo(projectID, modelsFunctionRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Test a subscription function
   * This endpoint test runs a transform function against a payload.
   * @param projectID Project ID (required)
   * @param modelsFunctionRequest Function Details (required)
   * @return ApiResponse&lt;V1ProjectsProjectIDSourcesTestFunctionPost200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<V1ProjectsProjectIDSourcesTestFunctionPost200Response> testSubscriptionFunctionWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFunctionRequest modelsFunctionRequest) throws ApiException {
    return testSubscriptionFunctionWithHttpInfo(projectID, modelsFunctionRequest, null);
  }

  /**
   * Test a subscription function
   * This endpoint test runs a transform function against a payload.
   * @param projectID Project ID (required)
   * @param modelsFunctionRequest Function Details (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;V1ProjectsProjectIDSourcesTestFunctionPost200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<V1ProjectsProjectIDSourcesTestFunctionPost200Response> testSubscriptionFunctionWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFunctionRequest modelsFunctionRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = testSubscriptionFunctionRequestBuilder(projectID, modelsFunctionRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("testSubscriptionFunction", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<V1ProjectsProjectIDSourcesTestFunctionPost200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        V1ProjectsProjectIDSourcesTestFunctionPost200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<V1ProjectsProjectIDSourcesTestFunctionPost200Response>() {});
        

        return new ApiResponse<V1ProjectsProjectIDSourcesTestFunctionPost200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder testSubscriptionFunctionRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFunctionRequest modelsFunctionRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling testSubscriptionFunction");
    }
    // verify the required parameter 'modelsFunctionRequest' is set
    if (modelsFunctionRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'modelsFunctionRequest' when calling testSubscriptionFunction");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/subscriptions/test_function"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(modelsFunctionRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Toggle subscription status
   * This endpoint toggles a subscription status. Retained for backward compatibility.
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @return GetProjects400Response
   * @throws ApiException if fails to make API call
   */
  public GetProjects400Response toggleSubscriptionStatus(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID) throws ApiException {
    return toggleSubscriptionStatus(projectID, subscriptionID, null);
  }

  /**
   * Toggle subscription status
   * This endpoint toggles a subscription status. Retained for backward compatibility.
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @param headers Optional headers to include in the request
   * @return GetProjects400Response
   * @throws ApiException if fails to make API call
   */
  public GetProjects400Response toggleSubscriptionStatus(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID, Map<String, String> headers) throws ApiException {
    ApiResponse<GetProjects400Response> localVarResponse = toggleSubscriptionStatusWithHttpInfo(projectID, subscriptionID, headers);
    return localVarResponse.getData();
  }

  /**
   * Toggle subscription status
   * This endpoint toggles a subscription status. Retained for backward compatibility.
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @return ApiResponse&lt;GetProjects400Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetProjects400Response> toggleSubscriptionStatusWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID) throws ApiException {
    return toggleSubscriptionStatusWithHttpInfo(projectID, subscriptionID, null);
  }

  /**
   * Toggle subscription status
   * This endpoint toggles a subscription status. Retained for backward compatibility.
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetProjects400Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetProjects400Response> toggleSubscriptionStatusWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = toggleSubscriptionStatusRequestBuilder(projectID, subscriptionID, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("toggleSubscriptionStatus", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetProjects400Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetProjects400Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetProjects400Response>() {});
        

        return new ApiResponse<GetProjects400Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder toggleSubscriptionStatusRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling toggleSubscriptionStatus");
    }
    // verify the required parameter 'subscriptionID' is set
    if (subscriptionID == null) {
      throw new ApiException(400, "Missing the required parameter 'subscriptionID' when calling toggleSubscriptionStatus");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/subscriptions/{subscriptionID}/toggle_status"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()))
        .replace("{subscriptionID}", ApiClient.urlEncode(subscriptionID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update a subscription
   * This endpoint updates a subscription
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @param modelsUpdateSubscription Subscription Details (required)
   * @return CreateSubscription201Response
   * @throws ApiException if fails to make API call
   */
  public CreateSubscription201Response updateSubscription(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID, @jakarta.annotation.Nonnull ModelsUpdateSubscription modelsUpdateSubscription) throws ApiException {
    return updateSubscription(projectID, subscriptionID, modelsUpdateSubscription, null);
  }

  /**
   * Update a subscription
   * This endpoint updates a subscription
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @param modelsUpdateSubscription Subscription Details (required)
   * @param headers Optional headers to include in the request
   * @return CreateSubscription201Response
   * @throws ApiException if fails to make API call
   */
  public CreateSubscription201Response updateSubscription(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID, @jakarta.annotation.Nonnull ModelsUpdateSubscription modelsUpdateSubscription, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateSubscription201Response> localVarResponse = updateSubscriptionWithHttpInfo(projectID, subscriptionID, modelsUpdateSubscription, headers);
    return localVarResponse.getData();
  }

  /**
   * Update a subscription
   * This endpoint updates a subscription
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @param modelsUpdateSubscription Subscription Details (required)
   * @return ApiResponse&lt;CreateSubscription201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateSubscription201Response> updateSubscriptionWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID, @jakarta.annotation.Nonnull ModelsUpdateSubscription modelsUpdateSubscription) throws ApiException {
    return updateSubscriptionWithHttpInfo(projectID, subscriptionID, modelsUpdateSubscription, null);
  }

  /**
   * Update a subscription
   * This endpoint updates a subscription
   * @param projectID Project ID (required)
   * @param subscriptionID subscription id (required)
   * @param modelsUpdateSubscription Subscription Details (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateSubscription201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateSubscription201Response> updateSubscriptionWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID, @jakarta.annotation.Nonnull ModelsUpdateSubscription modelsUpdateSubscription, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateSubscriptionRequestBuilder(projectID, subscriptionID, modelsUpdateSubscription, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateSubscription", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateSubscription201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateSubscription201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateSubscription201Response>() {});
        

        return new ApiResponse<CreateSubscription201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateSubscriptionRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull String subscriptionID, @jakarta.annotation.Nonnull ModelsUpdateSubscription modelsUpdateSubscription, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling updateSubscription");
    }
    // verify the required parameter 'subscriptionID' is set
    if (subscriptionID == null) {
      throw new ApiException(400, "Missing the required parameter 'subscriptionID' when calling updateSubscription");
    }
    // verify the required parameter 'modelsUpdateSubscription' is set
    if (modelsUpdateSubscription == null) {
      throw new ApiException(400, "Missing the required parameter 'modelsUpdateSubscription' when calling updateSubscription");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/subscriptions/{subscriptionID}"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()))
        .replace("{subscriptionID}", ApiClient.urlEncode(subscriptionID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(modelsUpdateSubscription);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Validate source function
   * This endpoint validates that a filter will match a certain payload structure.
   * @param projectID Project ID (required)
   * @param modelsFunctionRequest Function Details (required)
   * @return V1ProjectsProjectIDSourcesTestFunctionPost200Response
   * @throws ApiException if fails to make API call
   */
  public V1ProjectsProjectIDSourcesTestFunctionPost200Response v1ProjectsProjectIDSourcesTestFunctionPost(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFunctionRequest modelsFunctionRequest) throws ApiException {
    return v1ProjectsProjectIDSourcesTestFunctionPost(projectID, modelsFunctionRequest, null);
  }

  /**
   * Validate source function
   * This endpoint validates that a filter will match a certain payload structure.
   * @param projectID Project ID (required)
   * @param modelsFunctionRequest Function Details (required)
   * @param headers Optional headers to include in the request
   * @return V1ProjectsProjectIDSourcesTestFunctionPost200Response
   * @throws ApiException if fails to make API call
   */
  public V1ProjectsProjectIDSourcesTestFunctionPost200Response v1ProjectsProjectIDSourcesTestFunctionPost(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFunctionRequest modelsFunctionRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<V1ProjectsProjectIDSourcesTestFunctionPost200Response> localVarResponse = v1ProjectsProjectIDSourcesTestFunctionPostWithHttpInfo(projectID, modelsFunctionRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Validate source function
   * This endpoint validates that a filter will match a certain payload structure.
   * @param projectID Project ID (required)
   * @param modelsFunctionRequest Function Details (required)
   * @return ApiResponse&lt;V1ProjectsProjectIDSourcesTestFunctionPost200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<V1ProjectsProjectIDSourcesTestFunctionPost200Response> v1ProjectsProjectIDSourcesTestFunctionPostWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFunctionRequest modelsFunctionRequest) throws ApiException {
    return v1ProjectsProjectIDSourcesTestFunctionPostWithHttpInfo(projectID, modelsFunctionRequest, null);
  }

  /**
   * Validate source function
   * This endpoint validates that a filter will match a certain payload structure.
   * @param projectID Project ID (required)
   * @param modelsFunctionRequest Function Details (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;V1ProjectsProjectIDSourcesTestFunctionPost200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<V1ProjectsProjectIDSourcesTestFunctionPost200Response> v1ProjectsProjectIDSourcesTestFunctionPostWithHttpInfo(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFunctionRequest modelsFunctionRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = v1ProjectsProjectIDSourcesTestFunctionPostRequestBuilder(projectID, modelsFunctionRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("v1ProjectsProjectIDSourcesTestFunctionPost", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<V1ProjectsProjectIDSourcesTestFunctionPost200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        V1ProjectsProjectIDSourcesTestFunctionPost200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<V1ProjectsProjectIDSourcesTestFunctionPost200Response>() {});
        

        return new ApiResponse<V1ProjectsProjectIDSourcesTestFunctionPost200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder v1ProjectsProjectIDSourcesTestFunctionPostRequestBuilder(@jakarta.annotation.Nonnull String projectID, @jakarta.annotation.Nonnull ModelsFunctionRequest modelsFunctionRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectID' is set
    if (projectID == null) {
      throw new ApiException(400, "Missing the required parameter 'projectID' when calling v1ProjectsProjectIDSourcesTestFunctionPost");
    }
    // verify the required parameter 'modelsFunctionRequest' is set
    if (modelsFunctionRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'modelsFunctionRequest' when calling v1ProjectsProjectIDSourcesTestFunctionPost");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/projects/{projectID}/sources/test_function"
        .replace("{projectID}", ApiClient.urlEncode(projectID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(modelsFunctionRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
