/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.getconvoy.models.DatastoreApiKey;
import com.getconvoy.models.DatastoreBasicAuth;
import com.getconvoy.models.DatastoreEndpointAuthenticationType;
import com.getconvoy.models.DatastoreOAuth2;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * DatastoreEndpointAuthentication
 */
@JsonPropertyOrder({
  DatastoreEndpointAuthentication.JSON_PROPERTY_API_KEY,
  DatastoreEndpointAuthentication.JSON_PROPERTY_BASIC_AUTH,
  DatastoreEndpointAuthentication.JSON_PROPERTY_OAUTH2,
  DatastoreEndpointAuthentication.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class DatastoreEndpointAuthentication {
  public static final String JSON_PROPERTY_API_KEY = "api_key";
  @jakarta.annotation.Nullable
  private DatastoreApiKey apiKey;

  public static final String JSON_PROPERTY_BASIC_AUTH = "basic_auth";
  @jakarta.annotation.Nullable
  private DatastoreBasicAuth basicAuth;

  public static final String JSON_PROPERTY_OAUTH2 = "oauth2";
  @jakarta.annotation.Nullable
  private DatastoreOAuth2 oauth2;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private DatastoreEndpointAuthenticationType type;

  public DatastoreEndpointAuthentication() { 
  }

  public DatastoreEndpointAuthentication apiKey(@jakarta.annotation.Nullable DatastoreApiKey apiKey) {
    this.apiKey = apiKey;
    return this;
  }

  /**
   * Get apiKey
   * @return apiKey
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_API_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DatastoreApiKey getApiKey() {
    return apiKey;
  }


  @JsonProperty(value = JSON_PROPERTY_API_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiKey(@jakarta.annotation.Nullable DatastoreApiKey apiKey) {
    this.apiKey = apiKey;
  }


  public DatastoreEndpointAuthentication basicAuth(@jakarta.annotation.Nullable DatastoreBasicAuth basicAuth) {
    this.basicAuth = basicAuth;
    return this;
  }

  /**
   * Get basicAuth
   * @return basicAuth
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BASIC_AUTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DatastoreBasicAuth getBasicAuth() {
    return basicAuth;
  }


  @JsonProperty(value = JSON_PROPERTY_BASIC_AUTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBasicAuth(@jakarta.annotation.Nullable DatastoreBasicAuth basicAuth) {
    this.basicAuth = basicAuth;
  }


  public DatastoreEndpointAuthentication oauth2(@jakarta.annotation.Nullable DatastoreOAuth2 oauth2) {
    this.oauth2 = oauth2;
    return this;
  }

  /**
   * Get oauth2
   * @return oauth2
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OAUTH2, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DatastoreOAuth2 getOauth2() {
    return oauth2;
  }


  @JsonProperty(value = JSON_PROPERTY_OAUTH2, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOauth2(@jakarta.annotation.Nullable DatastoreOAuth2 oauth2) {
    this.oauth2 = oauth2;
  }


  public DatastoreEndpointAuthentication type(@jakarta.annotation.Nullable DatastoreEndpointAuthenticationType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DatastoreEndpointAuthenticationType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable DatastoreEndpointAuthenticationType type) {
    this.type = type;
  }


  /**
   * Return true if this datastore.EndpointAuthentication object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatastoreEndpointAuthentication datastoreEndpointAuthentication = (DatastoreEndpointAuthentication) o;
    return Objects.equals(this.apiKey, datastoreEndpointAuthentication.apiKey) &&
        Objects.equals(this.basicAuth, datastoreEndpointAuthentication.basicAuth) &&
        Objects.equals(this.oauth2, datastoreEndpointAuthentication.oauth2) &&
        Objects.equals(this.type, datastoreEndpointAuthentication.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKey, basicAuth, oauth2, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatastoreEndpointAuthentication {\n");
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    basicAuth: ").append(toIndentedString(basicAuth)).append("\n");
    sb.append("    oauth2: ").append(toIndentedString(oauth2)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `api_key` to the URL query string
    if (getApiKey() != null) {
      joiner.add(getApiKey().toUrlQueryString(prefix + "api_key" + suffix));
    }

    // add `basic_auth` to the URL query string
    if (getBasicAuth() != null) {
      joiner.add(getBasicAuth().toUrlQueryString(prefix + "basic_auth" + suffix));
    }

    // add `oauth2` to the URL query string
    if (getOauth2() != null) {
      joiner.add(getOauth2().toUrlQueryString(prefix + "oauth2" + suffix));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    return joiner.toString();
  }
}

