/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * DatastoreGooglePubSubConfig
 */
@JsonPropertyOrder({
  DatastoreGooglePubSubConfig.JSON_PROPERTY_PROJECT_ID,
  DatastoreGooglePubSubConfig.JSON_PROPERTY_SERVICE_ACCOUNT,
  DatastoreGooglePubSubConfig.JSON_PROPERTY_SUBSCRIPTION_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class DatastoreGooglePubSubConfig {
  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @jakarta.annotation.Nullable
  private String projectId;

  public static final String JSON_PROPERTY_SERVICE_ACCOUNT = "service_account";
  @jakarta.annotation.Nullable
  private byte[] serviceAccount;

  public static final String JSON_PROPERTY_SUBSCRIPTION_ID = "subscription_id";
  @jakarta.annotation.Nullable
  private String subscriptionId;

  public DatastoreGooglePubSubConfig() { 
  }

  public DatastoreGooglePubSubConfig projectId(@jakarta.annotation.Nullable String projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@jakarta.annotation.Nullable String projectId) {
    this.projectId = projectId;
  }


  public DatastoreGooglePubSubConfig serviceAccount(@jakarta.annotation.Nullable byte[] serviceAccount) {
    this.serviceAccount = serviceAccount;
    return this;
  }

  /**
   * encoding/json marshals []byte as a base64 string on the wire.
   * @return serviceAccount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVICE_ACCOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public byte[] getServiceAccount() {
    return serviceAccount;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVICE_ACCOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceAccount(@jakarta.annotation.Nullable byte[] serviceAccount) {
    this.serviceAccount = serviceAccount;
  }


  public DatastoreGooglePubSubConfig subscriptionId(@jakarta.annotation.Nullable String subscriptionId) {
    this.subscriptionId = subscriptionId;
    return this;
  }

  /**
   * Get subscriptionId
   * @return subscriptionId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBSCRIPTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSubscriptionId() {
    return subscriptionId;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBSCRIPTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubscriptionId(@jakarta.annotation.Nullable String subscriptionId) {
    this.subscriptionId = subscriptionId;
  }


  /**
   * Return true if this datastore.GooglePubSubConfig object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatastoreGooglePubSubConfig datastoreGooglePubSubConfig = (DatastoreGooglePubSubConfig) o;
    return Objects.equals(this.projectId, datastoreGooglePubSubConfig.projectId) &&
        Arrays.equals(this.serviceAccount, datastoreGooglePubSubConfig.serviceAccount) &&
        Objects.equals(this.subscriptionId, datastoreGooglePubSubConfig.subscriptionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, Arrays.hashCode(serviceAccount), subscriptionId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatastoreGooglePubSubConfig {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    serviceAccount: ").append(toIndentedString(serviceAccount)).append("\n");
    sb.append("    subscriptionId: ").append(toIndentedString(subscriptionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `service_account` to the URL query string
    if (getServiceAccount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sservice_account%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getServiceAccount()))));
    }

    // add `subscription_id` to the URL query string
    if (getSubscriptionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubscription_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubscriptionId()))));
    }

    return joiner.toString();
  }
}

