/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.getconvoy.models.DatastoreEncodingType;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * DatastoreHMac
 */
@JsonPropertyOrder({
  DatastoreHMac.JSON_PROPERTY_ENCODING,
  DatastoreHMac.JSON_PROPERTY_HASH,
  DatastoreHMac.JSON_PROPERTY_HEADER,
  DatastoreHMac.JSON_PROPERTY_SECRET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class DatastoreHMac {
  public static final String JSON_PROPERTY_ENCODING = "encoding";
  @jakarta.annotation.Nullable
  private DatastoreEncodingType encoding;

  public static final String JSON_PROPERTY_HASH = "hash";
  @jakarta.annotation.Nullable
  private String hash;

  public static final String JSON_PROPERTY_HEADER = "header";
  @jakarta.annotation.Nullable
  private String header;

  public static final String JSON_PROPERTY_SECRET = "secret";
  @jakarta.annotation.Nullable
  private String secret;

  public DatastoreHMac() { 
  }

  public DatastoreHMac encoding(@jakarta.annotation.Nullable DatastoreEncodingType encoding) {
    this.encoding = encoding;
    return this;
  }

  /**
   * Get encoding
   * @return encoding
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENCODING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DatastoreEncodingType getEncoding() {
    return encoding;
  }


  @JsonProperty(value = JSON_PROPERTY_ENCODING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncoding(@jakarta.annotation.Nullable DatastoreEncodingType encoding) {
    this.encoding = encoding;
  }


  public DatastoreHMac hash(@jakarta.annotation.Nullable String hash) {
    this.hash = hash;
    return this;
  }

  /**
   * Get hash
   * @return hash
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HASH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHash() {
    return hash;
  }


  @JsonProperty(value = JSON_PROPERTY_HASH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHash(@jakarta.annotation.Nullable String hash) {
    this.hash = hash;
  }


  public DatastoreHMac header(@jakarta.annotation.Nullable String header) {
    this.header = header;
    return this;
  }

  /**
   * Get header
   * @return header
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEADER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHeader() {
    return header;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeader(@jakarta.annotation.Nullable String header) {
    this.header = header;
  }


  public DatastoreHMac secret(@jakarta.annotation.Nullable String secret) {
    this.secret = secret;
    return this;
  }

  /**
   * Get secret
   * @return secret
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSecret() {
    return secret;
  }


  @JsonProperty(value = JSON_PROPERTY_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecret(@jakarta.annotation.Nullable String secret) {
    this.secret = secret;
  }


  /**
   * Return true if this datastore.HMac object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatastoreHMac datastoreHMac = (DatastoreHMac) o;
    return Objects.equals(this.encoding, datastoreHMac.encoding) &&
        Objects.equals(this.hash, datastoreHMac.hash) &&
        Objects.equals(this.header, datastoreHMac.header) &&
        Objects.equals(this.secret, datastoreHMac.secret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(encoding, hash, header, secret);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatastoreHMac {\n");
    sb.append("    encoding: ").append(toIndentedString(encoding)).append("\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `encoding` to the URL query string
    if (getEncoding() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sencoding%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEncoding()))));
    }

    // add `hash` to the URL query string
    if (getHash() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shash%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHash()))));
    }

    // add `header` to the URL query string
    if (getHeader() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sheader%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHeader()))));
    }

    // add `secret` to the URL query string
    if (getSecret() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssecret%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSecret()))));
    }

    return joiner.toString();
  }
}

