/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.getconvoy.models.DatastoreDeviceStatus;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * DatastoreDevice
 */
@JsonPropertyOrder({
  DatastoreDevice.JSON_PROPERTY_CREATED_AT,
  DatastoreDevice.JSON_PROPERTY_DELETED_AT,
  DatastoreDevice.JSON_PROPERTY_ENDPOINT_ID,
  DatastoreDevice.JSON_PROPERTY_HOST_NAME,
  DatastoreDevice.JSON_PROPERTY_LAST_SEEN_AT,
  DatastoreDevice.JSON_PROPERTY_PROJECT_ID,
  DatastoreDevice.JSON_PROPERTY_STATUS,
  DatastoreDevice.JSON_PROPERTY_UID,
  DatastoreDevice.JSON_PROPERTY_UPDATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class DatastoreDevice {
  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nullable
  private String createdAt;

  public static final String JSON_PROPERTY_DELETED_AT = "deleted_at";
  @jakarta.annotation.Nullable
  private String deletedAt;

  public static final String JSON_PROPERTY_ENDPOINT_ID = "endpoint_id";
  @jakarta.annotation.Nullable
  private String endpointId;

  public static final String JSON_PROPERTY_HOST_NAME = "host_name";
  @jakarta.annotation.Nullable
  private String hostName;

  public static final String JSON_PROPERTY_LAST_SEEN_AT = "last_seen_at";
  @jakarta.annotation.Nullable
  private String lastSeenAt;

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @jakarta.annotation.Nullable
  private String projectId;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private DatastoreDeviceStatus status;

  public static final String JSON_PROPERTY_UID = "uid";
  @jakarta.annotation.Nullable
  private String uid;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @jakarta.annotation.Nullable
  private String updatedAt;

  public DatastoreDevice() { 
  }

  public DatastoreDevice createdAt(@jakarta.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@jakarta.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public DatastoreDevice deletedAt(@jakarta.annotation.Nullable String deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DELETED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_DELETED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable String deletedAt) {
    this.deletedAt = deletedAt;
  }


  public DatastoreDevice endpointId(@jakarta.annotation.Nullable String endpointId) {
    this.endpointId = endpointId;
    return this;
  }

  /**
   * Get endpointId
   * @return endpointId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEndpointId() {
    return endpointId;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpointId(@jakarta.annotation.Nullable String endpointId) {
    this.endpointId = endpointId;
  }


  public DatastoreDevice hostName(@jakarta.annotation.Nullable String hostName) {
    this.hostName = hostName;
    return this;
  }

  /**
   * Get hostName
   * @return hostName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HOST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHostName() {
    return hostName;
  }


  @JsonProperty(value = JSON_PROPERTY_HOST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHostName(@jakarta.annotation.Nullable String hostName) {
    this.hostName = hostName;
  }


  public DatastoreDevice lastSeenAt(@jakarta.annotation.Nullable String lastSeenAt) {
    this.lastSeenAt = lastSeenAt;
    return this;
  }

  /**
   * Get lastSeenAt
   * @return lastSeenAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_SEEN_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLastSeenAt() {
    return lastSeenAt;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_SEEN_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastSeenAt(@jakarta.annotation.Nullable String lastSeenAt) {
    this.lastSeenAt = lastSeenAt;
  }


  public DatastoreDevice projectId(@jakarta.annotation.Nullable String projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@jakarta.annotation.Nullable String projectId) {
    this.projectId = projectId;
  }


  public DatastoreDevice status(@jakarta.annotation.Nullable DatastoreDeviceStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DatastoreDeviceStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable DatastoreDeviceStatus status) {
    this.status = status;
  }


  public DatastoreDevice uid(@jakarta.annotation.Nullable String uid) {
    this.uid = uid;
    return this;
  }

  /**
   * Get uid
   * @return uid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUid() {
    return uid;
  }


  @JsonProperty(value = JSON_PROPERTY_UID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUid(@jakarta.annotation.Nullable String uid) {
    this.uid = uid;
  }


  public DatastoreDevice updatedAt(@jakarta.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  /**
   * Return true if this datastore.Device object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatastoreDevice datastoreDevice = (DatastoreDevice) o;
    return Objects.equals(this.createdAt, datastoreDevice.createdAt) &&
        Objects.equals(this.deletedAt, datastoreDevice.deletedAt) &&
        Objects.equals(this.endpointId, datastoreDevice.endpointId) &&
        Objects.equals(this.hostName, datastoreDevice.hostName) &&
        Objects.equals(this.lastSeenAt, datastoreDevice.lastSeenAt) &&
        Objects.equals(this.projectId, datastoreDevice.projectId) &&
        Objects.equals(this.status, datastoreDevice.status) &&
        Objects.equals(this.uid, datastoreDevice.uid) &&
        Objects.equals(this.updatedAt, datastoreDevice.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, deletedAt, endpointId, hostName, lastSeenAt, projectId, status, uid, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatastoreDevice {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("    hostName: ").append(toIndentedString(hostName)).append("\n");
    sb.append("    lastSeenAt: ").append(toIndentedString(lastSeenAt)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `deleted_at` to the URL query string
    if (getDeletedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeleted_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeletedAt()))));
    }

    // add `endpoint_id` to the URL query string
    if (getEndpointId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sendpoint_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndpointId()))));
    }

    // add `host_name` to the URL query string
    if (getHostName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shost_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHostName()))));
    }

    // add `last_seen_at` to the URL query string
    if (getLastSeenAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slast_seen_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastSeenAt()))));
    }

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `uid` to the URL query string
    if (getUid() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUid()))));
    }

    // add `updated_at` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    return joiner.toString();
  }
}

