/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.getconvoy.models.DatastoreAmqpCredentials;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * DatastoreAmqpPubSubConfig
 */
@JsonPropertyOrder({
  DatastoreAmqpPubSubConfig.JSON_PROPERTY_HOST,
  DatastoreAmqpPubSubConfig.JSON_PROPERTY_AUTH,
  DatastoreAmqpPubSubConfig.JSON_PROPERTY_BINDED_EXCHANGE,
  DatastoreAmqpPubSubConfig.JSON_PROPERTY_DEAD_LETTER_EXCHANGE,
  DatastoreAmqpPubSubConfig.JSON_PROPERTY_PORT,
  DatastoreAmqpPubSubConfig.JSON_PROPERTY_QUEUE,
  DatastoreAmqpPubSubConfig.JSON_PROPERTY_ROUTING_KEY,
  DatastoreAmqpPubSubConfig.JSON_PROPERTY_SCHEMA,
  DatastoreAmqpPubSubConfig.JSON_PROPERTY_VHOST
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class DatastoreAmqpPubSubConfig {
  public static final String JSON_PROPERTY_HOST = "host";
  @jakarta.annotation.Nullable
  private String host;

  public static final String JSON_PROPERTY_AUTH = "auth";
  private JsonNullable<DatastoreAmqpCredentials> auth = JsonNullable.<DatastoreAmqpCredentials>undefined();

  public static final String JSON_PROPERTY_BINDED_EXCHANGE = "bindedExchange";
  private JsonNullable<String> bindedExchange = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DEAD_LETTER_EXCHANGE = "deadLetterExchange";
  private JsonNullable<String> deadLetterExchange = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PORT = "port";
  @jakarta.annotation.Nullable
  private String port;

  public static final String JSON_PROPERTY_QUEUE = "queue";
  @jakarta.annotation.Nullable
  private String queue;

  public static final String JSON_PROPERTY_ROUTING_KEY = "routingKey";
  @jakarta.annotation.Nullable
  private String routingKey;

  public static final String JSON_PROPERTY_SCHEMA = "schema";
  @jakarta.annotation.Nullable
  private String schema;

  public static final String JSON_PROPERTY_VHOST = "vhost";
  private JsonNullable<String> vhost = JsonNullable.<String>undefined();

  public DatastoreAmqpPubSubConfig() { 
  }

  public DatastoreAmqpPubSubConfig host(@jakarta.annotation.Nullable String host) {
    this.host = host;
    return this;
  }

  /**
   * Get host
   * @return host
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HOST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHost() {
    return host;
  }


  @JsonProperty(value = JSON_PROPERTY_HOST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHost(@jakarta.annotation.Nullable String host) {
    this.host = host;
  }


  public DatastoreAmqpPubSubConfig auth(@jakarta.annotation.Nullable DatastoreAmqpCredentials auth) {
    this.auth = JsonNullable.<DatastoreAmqpCredentials>of(auth);
    return this;
  }

  /**
   * Get auth
   * @return auth
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public DatastoreAmqpCredentials getAuth() {
        return auth.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_AUTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<DatastoreAmqpCredentials> getAuth_JsonNullable() {
    return auth;
  }
  
  @JsonProperty(JSON_PROPERTY_AUTH)
  public void setAuth_JsonNullable(JsonNullable<DatastoreAmqpCredentials> auth) {
    this.auth = auth;
  }

  public void setAuth(@jakarta.annotation.Nullable DatastoreAmqpCredentials auth) {
    this.auth = JsonNullable.<DatastoreAmqpCredentials>of(auth);
  }


  public DatastoreAmqpPubSubConfig bindedExchange(@jakarta.annotation.Nullable String bindedExchange) {
    this.bindedExchange = JsonNullable.<String>of(bindedExchange);
    return this;
  }

  /**
   * Get bindedExchange
   * @return bindedExchange
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getBindedExchange() {
        return bindedExchange.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_BINDED_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBindedExchange_JsonNullable() {
    return bindedExchange;
  }
  
  @JsonProperty(JSON_PROPERTY_BINDED_EXCHANGE)
  public void setBindedExchange_JsonNullable(JsonNullable<String> bindedExchange) {
    this.bindedExchange = bindedExchange;
  }

  public void setBindedExchange(@jakarta.annotation.Nullable String bindedExchange) {
    this.bindedExchange = JsonNullable.<String>of(bindedExchange);
  }


  public DatastoreAmqpPubSubConfig deadLetterExchange(@jakarta.annotation.Nullable String deadLetterExchange) {
    this.deadLetterExchange = JsonNullable.<String>of(deadLetterExchange);
    return this;
  }

  /**
   * Get deadLetterExchange
   * @return deadLetterExchange
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getDeadLetterExchange() {
        return deadLetterExchange.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DEAD_LETTER_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDeadLetterExchange_JsonNullable() {
    return deadLetterExchange;
  }
  
  @JsonProperty(JSON_PROPERTY_DEAD_LETTER_EXCHANGE)
  public void setDeadLetterExchange_JsonNullable(JsonNullable<String> deadLetterExchange) {
    this.deadLetterExchange = deadLetterExchange;
  }

  public void setDeadLetterExchange(@jakarta.annotation.Nullable String deadLetterExchange) {
    this.deadLetterExchange = JsonNullable.<String>of(deadLetterExchange);
  }


  public DatastoreAmqpPubSubConfig port(@jakarta.annotation.Nullable String port) {
    this.port = port;
    return this;
  }

  /**
   * Get port
   * @return port
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPort() {
    return port;
  }


  @JsonProperty(value = JSON_PROPERTY_PORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPort(@jakarta.annotation.Nullable String port) {
    this.port = port;
  }


  public DatastoreAmqpPubSubConfig queue(@jakarta.annotation.Nullable String queue) {
    this.queue = queue;
    return this;
  }

  /**
   * Get queue
   * @return queue
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUEUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getQueue() {
    return queue;
  }


  @JsonProperty(value = JSON_PROPERTY_QUEUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueue(@jakarta.annotation.Nullable String queue) {
    this.queue = queue;
  }


  public DatastoreAmqpPubSubConfig routingKey(@jakarta.annotation.Nullable String routingKey) {
    this.routingKey = routingKey;
    return this;
  }

  /**
   * Get routingKey
   * @return routingKey
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROUTING_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRoutingKey() {
    return routingKey;
  }


  @JsonProperty(value = JSON_PROPERTY_ROUTING_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoutingKey(@jakarta.annotation.Nullable String routingKey) {
    this.routingKey = routingKey;
  }


  public DatastoreAmqpPubSubConfig schema(@jakarta.annotation.Nullable String schema) {
    this.schema = schema;
    return this;
  }

  /**
   * Get schema
   * @return schema
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEMA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSchema() {
    return schema;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEMA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchema(@jakarta.annotation.Nullable String schema) {
    this.schema = schema;
  }


  public DatastoreAmqpPubSubConfig vhost(@jakarta.annotation.Nullable String vhost) {
    this.vhost = JsonNullable.<String>of(vhost);
    return this;
  }

  /**
   * Get vhost
   * @return vhost
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getVhost() {
        return vhost.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_VHOST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getVhost_JsonNullable() {
    return vhost;
  }
  
  @JsonProperty(JSON_PROPERTY_VHOST)
  public void setVhost_JsonNullable(JsonNullable<String> vhost) {
    this.vhost = vhost;
  }

  public void setVhost(@jakarta.annotation.Nullable String vhost) {
    this.vhost = JsonNullable.<String>of(vhost);
  }


  /**
   * Return true if this datastore.AmqpPubSubConfig object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatastoreAmqpPubSubConfig datastoreAmqpPubSubConfig = (DatastoreAmqpPubSubConfig) o;
    return Objects.equals(this.host, datastoreAmqpPubSubConfig.host) &&
        equalsNullable(this.auth, datastoreAmqpPubSubConfig.auth) &&
        equalsNullable(this.bindedExchange, datastoreAmqpPubSubConfig.bindedExchange) &&
        equalsNullable(this.deadLetterExchange, datastoreAmqpPubSubConfig.deadLetterExchange) &&
        Objects.equals(this.port, datastoreAmqpPubSubConfig.port) &&
        Objects.equals(this.queue, datastoreAmqpPubSubConfig.queue) &&
        Objects.equals(this.routingKey, datastoreAmqpPubSubConfig.routingKey) &&
        Objects.equals(this.schema, datastoreAmqpPubSubConfig.schema) &&
        equalsNullable(this.vhost, datastoreAmqpPubSubConfig.vhost);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(host, hashCodeNullable(auth), hashCodeNullable(bindedExchange), hashCodeNullable(deadLetterExchange), port, queue, routingKey, schema, hashCodeNullable(vhost));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatastoreAmqpPubSubConfig {\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    auth: ").append(toIndentedString(auth)).append("\n");
    sb.append("    bindedExchange: ").append(toIndentedString(bindedExchange)).append("\n");
    sb.append("    deadLetterExchange: ").append(toIndentedString(deadLetterExchange)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    queue: ").append(toIndentedString(queue)).append("\n");
    sb.append("    routingKey: ").append(toIndentedString(routingKey)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    vhost: ").append(toIndentedString(vhost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `host` to the URL query string
    if (getHost() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shost%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHost()))));
    }

    // add `auth` to the URL query string
    if (getAuth() != null) {
      joiner.add(getAuth().toUrlQueryString(prefix + "auth" + suffix));
    }

    // add `bindedExchange` to the URL query string
    if (getBindedExchange() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbindedExchange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBindedExchange()))));
    }

    // add `deadLetterExchange` to the URL query string
    if (getDeadLetterExchange() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeadLetterExchange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeadLetterExchange()))));
    }

    // add `port` to the URL query string
    if (getPort() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sport%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPort()))));
    }

    // add `queue` to the URL query string
    if (getQueue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squeue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQueue()))));
    }

    // add `routingKey` to the URL query string
    if (getRoutingKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sroutingKey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRoutingKey()))));
    }

    // add `schema` to the URL query string
    if (getSchema() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sschema%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSchema()))));
    }

    // add `vhost` to the URL query string
    if (getVhost() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svhost%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVhost()))));
    }

    return joiner.toString();
  }
}

