/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.getconvoy.models.DatastoreEndpoint;
import com.getconvoy.models.DatastorePortalAuthType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * DatastorePortalLinkResponse
 */
@JsonPropertyOrder({
  DatastorePortalLinkResponse.JSON_PROPERTY_AUTH_KEY,
  DatastorePortalLinkResponse.JSON_PROPERTY_AUTH_TYPE,
  DatastorePortalLinkResponse.JSON_PROPERTY_CAN_MANAGE_ENDPOINT,
  DatastorePortalLinkResponse.JSON_PROPERTY_CREATED_AT,
  DatastorePortalLinkResponse.JSON_PROPERTY_DELETED_AT,
  DatastorePortalLinkResponse.JSON_PROPERTY_ENDPOINT_COUNT,
  DatastorePortalLinkResponse.JSON_PROPERTY_ENDPOINTS,
  DatastorePortalLinkResponse.JSON_PROPERTY_ENDPOINTS_METADATA,
  DatastorePortalLinkResponse.JSON_PROPERTY_NAME,
  DatastorePortalLinkResponse.JSON_PROPERTY_OWNER_ID,
  DatastorePortalLinkResponse.JSON_PROPERTY_PROJECT_ID,
  DatastorePortalLinkResponse.JSON_PROPERTY_TOKEN,
  DatastorePortalLinkResponse.JSON_PROPERTY_UID,
  DatastorePortalLinkResponse.JSON_PROPERTY_UPDATED_AT,
  DatastorePortalLinkResponse.JSON_PROPERTY_URL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class DatastorePortalLinkResponse {
  public static final String JSON_PROPERTY_AUTH_KEY = "auth_key";
  @jakarta.annotation.Nullable
  private String authKey;

  public static final String JSON_PROPERTY_AUTH_TYPE = "auth_type";
  @jakarta.annotation.Nullable
  private DatastorePortalAuthType authType;

  public static final String JSON_PROPERTY_CAN_MANAGE_ENDPOINT = "can_manage_endpoint";
  @jakarta.annotation.Nullable
  private Boolean canManageEndpoint;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nullable
  private String createdAt;

  public static final String JSON_PROPERTY_DELETED_AT = "deleted_at";
  private JsonNullable<String> deletedAt = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ENDPOINT_COUNT = "endpoint_count";
  @jakarta.annotation.Nullable
  private Integer endpointCount;

  public static final String JSON_PROPERTY_ENDPOINTS = "endpoints";
  @jakarta.annotation.Nullable
  private List<String> endpoints = new ArrayList<>();

  public static final String JSON_PROPERTY_ENDPOINTS_METADATA = "endpoints_metadata";
  @jakarta.annotation.Nullable
  private List<DatastoreEndpoint> endpointsMetadata = new ArrayList<>();

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_OWNER_ID = "owner_id";
  @jakarta.annotation.Nullable
  private String ownerId;

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @jakarta.annotation.Nullable
  private String projectId;

  public static final String JSON_PROPERTY_TOKEN = "token";
  @jakarta.annotation.Nullable
  private String token;

  public static final String JSON_PROPERTY_UID = "uid";
  @jakarta.annotation.Nullable
  private String uid;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @jakarta.annotation.Nullable
  private String updatedAt;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public DatastorePortalLinkResponse() { 
  }

  public DatastorePortalLinkResponse authKey(@jakarta.annotation.Nullable String authKey) {
    this.authKey = authKey;
    return this;
  }

  /**
   * Get authKey
   * @return authKey
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTH_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAuthKey() {
    return authKey;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTH_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthKey(@jakarta.annotation.Nullable String authKey) {
    this.authKey = authKey;
  }


  public DatastorePortalLinkResponse authType(@jakarta.annotation.Nullable DatastorePortalAuthType authType) {
    this.authType = authType;
    return this;
  }

  /**
   * Get authType
   * @return authType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTH_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DatastorePortalAuthType getAuthType() {
    return authType;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTH_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthType(@jakarta.annotation.Nullable DatastorePortalAuthType authType) {
    this.authType = authType;
  }


  public DatastorePortalLinkResponse canManageEndpoint(@jakarta.annotation.Nullable Boolean canManageEndpoint) {
    this.canManageEndpoint = canManageEndpoint;
    return this;
  }

  /**
   * Get canManageEndpoint
   * @return canManageEndpoint
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CAN_MANAGE_ENDPOINT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getCanManageEndpoint() {
    return canManageEndpoint;
  }


  @JsonProperty(value = JSON_PROPERTY_CAN_MANAGE_ENDPOINT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCanManageEndpoint(@jakarta.annotation.Nullable Boolean canManageEndpoint) {
    this.canManageEndpoint = canManageEndpoint;
  }


  public DatastorePortalLinkResponse createdAt(@jakarta.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@jakarta.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public DatastorePortalLinkResponse deletedAt(@jakarta.annotation.Nullable String deletedAt) {
    this.deletedAt = JsonNullable.<String>of(deletedAt);
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getDeletedAt() {
        return deletedAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DELETED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDeletedAt_JsonNullable() {
    return deletedAt;
  }
  
  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  public void setDeletedAt_JsonNullable(JsonNullable<String> deletedAt) {
    this.deletedAt = deletedAt;
  }

  public void setDeletedAt(@jakarta.annotation.Nullable String deletedAt) {
    this.deletedAt = JsonNullable.<String>of(deletedAt);
  }


  public DatastorePortalLinkResponse endpointCount(@jakarta.annotation.Nullable Integer endpointCount) {
    this.endpointCount = endpointCount;
    return this;
  }

  /**
   * Get endpointCount
   * @return endpointCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getEndpointCount() {
    return endpointCount;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpointCount(@jakarta.annotation.Nullable Integer endpointCount) {
    this.endpointCount = endpointCount;
  }


  public DatastorePortalLinkResponse endpoints(@jakarta.annotation.Nullable List<String> endpoints) {
    this.endpoints = endpoints;
    return this;
  }

  public DatastorePortalLinkResponse addEndpointsItem(String endpointsItem) {
    if (this.endpoints == null) {
      this.endpoints = new ArrayList<>();
    }
    this.endpoints.add(endpointsItem);
    return this;
  }

  /**
   * Get endpoints
   * @return endpoints
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDPOINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getEndpoints() {
    return endpoints;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpoints(@jakarta.annotation.Nullable List<String> endpoints) {
    this.endpoints = endpoints;
  }


  public DatastorePortalLinkResponse endpointsMetadata(@jakarta.annotation.Nullable List<DatastoreEndpoint> endpointsMetadata) {
    this.endpointsMetadata = endpointsMetadata;
    return this;
  }

  public DatastorePortalLinkResponse addEndpointsMetadataItem(DatastoreEndpoint endpointsMetadataItem) {
    if (this.endpointsMetadata == null) {
      this.endpointsMetadata = new ArrayList<>();
    }
    this.endpointsMetadata.add(endpointsMetadataItem);
    return this;
  }

  /**
   * Get endpointsMetadata
   * @return endpointsMetadata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDPOINTS_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<DatastoreEndpoint> getEndpointsMetadata() {
    return endpointsMetadata;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINTS_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpointsMetadata(@jakarta.annotation.Nullable List<DatastoreEndpoint> endpointsMetadata) {
    this.endpointsMetadata = endpointsMetadata;
  }


  public DatastorePortalLinkResponse name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public DatastorePortalLinkResponse ownerId(@jakarta.annotation.Nullable String ownerId) {
    this.ownerId = ownerId;
    return this;
  }

  /**
   * Get ownerId
   * @return ownerId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OWNER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOwnerId() {
    return ownerId;
  }


  @JsonProperty(value = JSON_PROPERTY_OWNER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerId(@jakarta.annotation.Nullable String ownerId) {
    this.ownerId = ownerId;
  }


  public DatastorePortalLinkResponse projectId(@jakarta.annotation.Nullable String projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@jakarta.annotation.Nullable String projectId) {
    this.projectId = projectId;
  }


  public DatastorePortalLinkResponse token(@jakarta.annotation.Nullable String token) {
    this.token = token;
    return this;
  }

  /**
   * Get token
   * @return token
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getToken() {
    return token;
  }


  @JsonProperty(value = JSON_PROPERTY_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToken(@jakarta.annotation.Nullable String token) {
    this.token = token;
  }


  public DatastorePortalLinkResponse uid(@jakarta.annotation.Nullable String uid) {
    this.uid = uid;
    return this;
  }

  /**
   * Get uid
   * @return uid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUid() {
    return uid;
  }


  @JsonProperty(value = JSON_PROPERTY_UID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUid(@jakarta.annotation.Nullable String uid) {
    this.uid = uid;
  }


  public DatastorePortalLinkResponse updatedAt(@jakarta.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public DatastorePortalLinkResponse url(@jakarta.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = url;
  }


  /**
   * Return true if this datastore.PortalLinkResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatastorePortalLinkResponse datastorePortalLinkResponse = (DatastorePortalLinkResponse) o;
    return Objects.equals(this.authKey, datastorePortalLinkResponse.authKey) &&
        Objects.equals(this.authType, datastorePortalLinkResponse.authType) &&
        Objects.equals(this.canManageEndpoint, datastorePortalLinkResponse.canManageEndpoint) &&
        Objects.equals(this.createdAt, datastorePortalLinkResponse.createdAt) &&
        equalsNullable(this.deletedAt, datastorePortalLinkResponse.deletedAt) &&
        Objects.equals(this.endpointCount, datastorePortalLinkResponse.endpointCount) &&
        Objects.equals(this.endpoints, datastorePortalLinkResponse.endpoints) &&
        Objects.equals(this.endpointsMetadata, datastorePortalLinkResponse.endpointsMetadata) &&
        Objects.equals(this.name, datastorePortalLinkResponse.name) &&
        Objects.equals(this.ownerId, datastorePortalLinkResponse.ownerId) &&
        Objects.equals(this.projectId, datastorePortalLinkResponse.projectId) &&
        Objects.equals(this.token, datastorePortalLinkResponse.token) &&
        Objects.equals(this.uid, datastorePortalLinkResponse.uid) &&
        Objects.equals(this.updatedAt, datastorePortalLinkResponse.updatedAt) &&
        Objects.equals(this.url, datastorePortalLinkResponse.url);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(authKey, authType, canManageEndpoint, createdAt, hashCodeNullable(deletedAt), endpointCount, endpoints, endpointsMetadata, name, ownerId, projectId, token, uid, updatedAt, url);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatastorePortalLinkResponse {\n");
    sb.append("    authKey: ").append(toIndentedString(authKey)).append("\n");
    sb.append("    authType: ").append(toIndentedString(authType)).append("\n");
    sb.append("    canManageEndpoint: ").append(toIndentedString(canManageEndpoint)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    endpointCount: ").append(toIndentedString(endpointCount)).append("\n");
    sb.append("    endpoints: ").append(toIndentedString(endpoints)).append("\n");
    sb.append("    endpointsMetadata: ").append(toIndentedString(endpointsMetadata)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `auth_key` to the URL query string
    if (getAuthKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sauth_key%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAuthKey()))));
    }

    // add `auth_type` to the URL query string
    if (getAuthType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sauth_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAuthType()))));
    }

    // add `can_manage_endpoint` to the URL query string
    if (getCanManageEndpoint() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scan_manage_endpoint%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCanManageEndpoint()))));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `deleted_at` to the URL query string
    if (getDeletedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeleted_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeletedAt()))));
    }

    // add `endpoint_count` to the URL query string
    if (getEndpointCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sendpoint_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndpointCount()))));
    }

    // add `endpoints` to the URL query string
    if (getEndpoints() != null) {
      for (int i = 0; i < getEndpoints().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sendpoints%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getEndpoints().get(i)))));
      }
    }

    // add `endpoints_metadata` to the URL query string
    if (getEndpointsMetadata() != null) {
      for (int i = 0; i < getEndpointsMetadata().size(); i++) {
        if (getEndpointsMetadata().get(i) != null) {
          joiner.add(getEndpointsMetadata().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sendpoints_metadata%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `owner_id` to the URL query string
    if (getOwnerId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sowner_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOwnerId()))));
    }

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `token` to the URL query string
    if (getToken() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stoken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getToken()))));
    }

    // add `uid` to the URL query string
    if (getUid() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUid()))));
    }

    // add `updated_at` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    // add `url` to the URL query string
    if (getUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrl()))));
    }

    return joiner.toString();
  }
}

