/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * ModelsTestFilterResponse
 */
@JsonPropertyOrder({
  ModelsTestFilterResponse.JSON_PROPERTY_IS_MATCH
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ModelsTestFilterResponse {
  public static final String JSON_PROPERTY_IS_MATCH = "is_match";
  @jakarta.annotation.Nullable
  private Boolean isMatch;

  public ModelsTestFilterResponse() { 
  }

  public ModelsTestFilterResponse isMatch(@jakarta.annotation.Nullable Boolean isMatch) {
    this.isMatch = isMatch;
    return this;
  }

  /**
   * Whether the payload matches the filter criteria
   * @return isMatch
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_MATCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsMatch() {
    return isMatch;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_MATCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsMatch(@jakarta.annotation.Nullable Boolean isMatch) {
    this.isMatch = isMatch;
  }


  /**
   * Return true if this models.TestFilterResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsTestFilterResponse modelsTestFilterResponse = (ModelsTestFilterResponse) o;
    return Objects.equals(this.isMatch, modelsTestFilterResponse.isMatch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isMatch);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsTestFilterResponse {\n");
    sb.append("    isMatch: ").append(toIndentedString(isMatch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `is_match` to the URL query string
    if (getIsMatch() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sis_match%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsMatch()))));
    }

    return joiner.toString();
  }
}

