/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.getconvoy.models.DatastoreCLIMetadata;
import com.getconvoy.models.DatastoreDeliveryMode;
import com.getconvoy.models.DatastoreDevice;
import com.getconvoy.models.DatastoreEndpoint;
import com.getconvoy.models.DatastoreEvent;
import com.getconvoy.models.DatastoreEventDeliveryStatus;
import com.getconvoy.models.DatastoreMetadata;
import com.getconvoy.models.DatastoreSource;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * ModelsEventDeliveryResponse
 */
@JsonPropertyOrder({
  ModelsEventDeliveryResponse.JSON_PROPERTY_ACKNOWLEDGED_AT,
  ModelsEventDeliveryResponse.JSON_PROPERTY_CLI_METADATA,
  ModelsEventDeliveryResponse.JSON_PROPERTY_CREATED_AT,
  ModelsEventDeliveryResponse.JSON_PROPERTY_DELETED_AT,
  ModelsEventDeliveryResponse.JSON_PROPERTY_DELIVERY_MODE,
  ModelsEventDeliveryResponse.JSON_PROPERTY_DESCRIPTION,
  ModelsEventDeliveryResponse.JSON_PROPERTY_DEVICE_ID,
  ModelsEventDeliveryResponse.JSON_PROPERTY_DEVICE_METADATA,
  ModelsEventDeliveryResponse.JSON_PROPERTY_ENDPOINT_ID,
  ModelsEventDeliveryResponse.JSON_PROPERTY_ENDPOINT_METADATA,
  ModelsEventDeliveryResponse.JSON_PROPERTY_EVENT_ID,
  ModelsEventDeliveryResponse.JSON_PROPERTY_EVENT_METADATA,
  ModelsEventDeliveryResponse.JSON_PROPERTY_EVENT_TYPE,
  ModelsEventDeliveryResponse.JSON_PROPERTY_HEADERS,
  ModelsEventDeliveryResponse.JSON_PROPERTY_IDEMPOTENCY_KEY,
  ModelsEventDeliveryResponse.JSON_PROPERTY_LATENCY,
  ModelsEventDeliveryResponse.JSON_PROPERTY_LATENCY_SECONDS,
  ModelsEventDeliveryResponse.JSON_PROPERTY_METADATA,
  ModelsEventDeliveryResponse.JSON_PROPERTY_PROJECT_ID,
  ModelsEventDeliveryResponse.JSON_PROPERTY_SOURCE_METADATA,
  ModelsEventDeliveryResponse.JSON_PROPERTY_STATUS,
  ModelsEventDeliveryResponse.JSON_PROPERTY_SUBSCRIPTION_ID,
  ModelsEventDeliveryResponse.JSON_PROPERTY_TARGET_URL,
  ModelsEventDeliveryResponse.JSON_PROPERTY_UID,
  ModelsEventDeliveryResponse.JSON_PROPERTY_UPDATED_AT,
  ModelsEventDeliveryResponse.JSON_PROPERTY_URL_QUERY_PARAMS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ModelsEventDeliveryResponse {
  public static final String JSON_PROPERTY_ACKNOWLEDGED_AT = "acknowledged_at";
  private JsonNullable<String> acknowledgedAt = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CLI_METADATA = "cli_metadata";
  private JsonNullable<DatastoreCLIMetadata> cliMetadata = JsonNullable.<DatastoreCLIMetadata>undefined();

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nullable
  private String createdAt;

  public static final String JSON_PROPERTY_DELETED_AT = "deleted_at";
  private JsonNullable<String> deletedAt = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DELIVERY_MODE = "delivery_mode";
  @jakarta.annotation.Nullable
  private DatastoreDeliveryMode deliveryMode;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_DEVICE_ID = "device_id";
  @jakarta.annotation.Nullable
  private String deviceId;

  public static final String JSON_PROPERTY_DEVICE_METADATA = "device_metadata";
  private JsonNullable<DatastoreDevice> deviceMetadata = JsonNullable.<DatastoreDevice>undefined();

  public static final String JSON_PROPERTY_ENDPOINT_ID = "endpoint_id";
  @jakarta.annotation.Nullable
  private String endpointId;

  public static final String JSON_PROPERTY_ENDPOINT_METADATA = "endpoint_metadata";
  private JsonNullable<DatastoreEndpoint> endpointMetadata = JsonNullable.<DatastoreEndpoint>undefined();

  public static final String JSON_PROPERTY_EVENT_ID = "event_id";
  @jakarta.annotation.Nullable
  private String eventId;

  public static final String JSON_PROPERTY_EVENT_METADATA = "event_metadata";
  private JsonNullable<DatastoreEvent> eventMetadata = JsonNullable.<DatastoreEvent>undefined();

  public static final String JSON_PROPERTY_EVENT_TYPE = "event_type";
  @jakarta.annotation.Nullable
  private String eventType;

  public static final String JSON_PROPERTY_HEADERS = "headers";
  private JsonNullable<Map<String, List<String>>> headers = JsonNullable.<Map<String, List<String>>>undefined();

  public static final String JSON_PROPERTY_IDEMPOTENCY_KEY = "idempotency_key";
  @jakarta.annotation.Nullable
  private String idempotencyKey;

  public static final String JSON_PROPERTY_LATENCY = "latency";
  @jakarta.annotation.Nullable
  private String latency;

  public static final String JSON_PROPERTY_LATENCY_SECONDS = "latency_seconds";
  @jakarta.annotation.Nullable
  private BigDecimal latencySeconds;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private JsonNullable<DatastoreMetadata> metadata = JsonNullable.<DatastoreMetadata>undefined();

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  @jakarta.annotation.Nullable
  private String projectId;

  public static final String JSON_PROPERTY_SOURCE_METADATA = "source_metadata";
  private JsonNullable<DatastoreSource> sourceMetadata = JsonNullable.<DatastoreSource>undefined();

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private DatastoreEventDeliveryStatus status;

  public static final String JSON_PROPERTY_SUBSCRIPTION_ID = "subscription_id";
  @jakarta.annotation.Nullable
  private String subscriptionId;

  public static final String JSON_PROPERTY_TARGET_URL = "target_url";
  @jakarta.annotation.Nullable
  private String targetUrl;

  public static final String JSON_PROPERTY_UID = "uid";
  @jakarta.annotation.Nullable
  private String uid;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @jakarta.annotation.Nullable
  private String updatedAt;

  public static final String JSON_PROPERTY_URL_QUERY_PARAMS = "url_query_params";
  @jakarta.annotation.Nullable
  private String urlQueryParams;

  public ModelsEventDeliveryResponse() { 
  }

  public ModelsEventDeliveryResponse acknowledgedAt(@jakarta.annotation.Nullable String acknowledgedAt) {
    this.acknowledgedAt = JsonNullable.<String>of(acknowledgedAt);
    return this;
  }

  /**
   * Get acknowledgedAt
   * @return acknowledgedAt
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getAcknowledgedAt() {
        return acknowledgedAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ACKNOWLEDGED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAcknowledgedAt_JsonNullable() {
    return acknowledgedAt;
  }
  
  @JsonProperty(JSON_PROPERTY_ACKNOWLEDGED_AT)
  public void setAcknowledgedAt_JsonNullable(JsonNullable<String> acknowledgedAt) {
    this.acknowledgedAt = acknowledgedAt;
  }

  public void setAcknowledgedAt(@jakarta.annotation.Nullable String acknowledgedAt) {
    this.acknowledgedAt = JsonNullable.<String>of(acknowledgedAt);
  }


  public ModelsEventDeliveryResponse cliMetadata(@jakarta.annotation.Nullable DatastoreCLIMetadata cliMetadata) {
    this.cliMetadata = JsonNullable.<DatastoreCLIMetadata>of(cliMetadata);
    return this;
  }

  /**
   * Get cliMetadata
   * @return cliMetadata
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public DatastoreCLIMetadata getCliMetadata() {
        return cliMetadata.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CLI_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<DatastoreCLIMetadata> getCliMetadata_JsonNullable() {
    return cliMetadata;
  }
  
  @JsonProperty(JSON_PROPERTY_CLI_METADATA)
  public void setCliMetadata_JsonNullable(JsonNullable<DatastoreCLIMetadata> cliMetadata) {
    this.cliMetadata = cliMetadata;
  }

  public void setCliMetadata(@jakarta.annotation.Nullable DatastoreCLIMetadata cliMetadata) {
    this.cliMetadata = JsonNullable.<DatastoreCLIMetadata>of(cliMetadata);
  }


  public ModelsEventDeliveryResponse createdAt(@jakarta.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@jakarta.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public ModelsEventDeliveryResponse deletedAt(@jakarta.annotation.Nullable String deletedAt) {
    this.deletedAt = JsonNullable.<String>of(deletedAt);
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getDeletedAt() {
        return deletedAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DELETED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDeletedAt_JsonNullable() {
    return deletedAt;
  }
  
  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  public void setDeletedAt_JsonNullable(JsonNullable<String> deletedAt) {
    this.deletedAt = deletedAt;
  }

  public void setDeletedAt(@jakarta.annotation.Nullable String deletedAt) {
    this.deletedAt = JsonNullable.<String>of(deletedAt);
  }


  public ModelsEventDeliveryResponse deliveryMode(@jakarta.annotation.Nullable DatastoreDeliveryMode deliveryMode) {
    this.deliveryMode = deliveryMode;
    return this;
  }

  /**
   * Get deliveryMode
   * @return deliveryMode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DELIVERY_MODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DatastoreDeliveryMode getDeliveryMode() {
    return deliveryMode;
  }


  @JsonProperty(value = JSON_PROPERTY_DELIVERY_MODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryMode(@jakarta.annotation.Nullable DatastoreDeliveryMode deliveryMode) {
    this.deliveryMode = deliveryMode;
  }


  public ModelsEventDeliveryResponse description(@jakarta.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }


  public ModelsEventDeliveryResponse deviceId(@jakarta.annotation.Nullable String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

  /**
   * Get deviceId
   * @return deviceId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVICE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDeviceId() {
    return deviceId;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVICE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceId(@jakarta.annotation.Nullable String deviceId) {
    this.deviceId = deviceId;
  }


  public ModelsEventDeliveryResponse deviceMetadata(@jakarta.annotation.Nullable DatastoreDevice deviceMetadata) {
    this.deviceMetadata = JsonNullable.<DatastoreDevice>of(deviceMetadata);
    return this;
  }

  /**
   * Get deviceMetadata
   * @return deviceMetadata
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public DatastoreDevice getDeviceMetadata() {
        return deviceMetadata.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DEVICE_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<DatastoreDevice> getDeviceMetadata_JsonNullable() {
    return deviceMetadata;
  }
  
  @JsonProperty(JSON_PROPERTY_DEVICE_METADATA)
  public void setDeviceMetadata_JsonNullable(JsonNullable<DatastoreDevice> deviceMetadata) {
    this.deviceMetadata = deviceMetadata;
  }

  public void setDeviceMetadata(@jakarta.annotation.Nullable DatastoreDevice deviceMetadata) {
    this.deviceMetadata = JsonNullable.<DatastoreDevice>of(deviceMetadata);
  }


  public ModelsEventDeliveryResponse endpointId(@jakarta.annotation.Nullable String endpointId) {
    this.endpointId = endpointId;
    return this;
  }

  /**
   * Get endpointId
   * @return endpointId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEndpointId() {
    return endpointId;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpointId(@jakarta.annotation.Nullable String endpointId) {
    this.endpointId = endpointId;
  }


  public ModelsEventDeliveryResponse endpointMetadata(@jakarta.annotation.Nullable DatastoreEndpoint endpointMetadata) {
    this.endpointMetadata = JsonNullable.<DatastoreEndpoint>of(endpointMetadata);
    return this;
  }

  /**
   * Get endpointMetadata
   * @return endpointMetadata
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public DatastoreEndpoint getEndpointMetadata() {
        return endpointMetadata.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<DatastoreEndpoint> getEndpointMetadata_JsonNullable() {
    return endpointMetadata;
  }
  
  @JsonProperty(JSON_PROPERTY_ENDPOINT_METADATA)
  public void setEndpointMetadata_JsonNullable(JsonNullable<DatastoreEndpoint> endpointMetadata) {
    this.endpointMetadata = endpointMetadata;
  }

  public void setEndpointMetadata(@jakarta.annotation.Nullable DatastoreEndpoint endpointMetadata) {
    this.endpointMetadata = JsonNullable.<DatastoreEndpoint>of(endpointMetadata);
  }


  public ModelsEventDeliveryResponse eventId(@jakarta.annotation.Nullable String eventId) {
    this.eventId = eventId;
    return this;
  }

  /**
   * Get eventId
   * @return eventId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEventId() {
    return eventId;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventId(@jakarta.annotation.Nullable String eventId) {
    this.eventId = eventId;
  }


  public ModelsEventDeliveryResponse eventMetadata(@jakarta.annotation.Nullable DatastoreEvent eventMetadata) {
    this.eventMetadata = JsonNullable.<DatastoreEvent>of(eventMetadata);
    return this;
  }

  /**
   * Get eventMetadata
   * @return eventMetadata
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public DatastoreEvent getEventMetadata() {
        return eventMetadata.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_EVENT_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<DatastoreEvent> getEventMetadata_JsonNullable() {
    return eventMetadata;
  }
  
  @JsonProperty(JSON_PROPERTY_EVENT_METADATA)
  public void setEventMetadata_JsonNullable(JsonNullable<DatastoreEvent> eventMetadata) {
    this.eventMetadata = eventMetadata;
  }

  public void setEventMetadata(@jakarta.annotation.Nullable DatastoreEvent eventMetadata) {
    this.eventMetadata = JsonNullable.<DatastoreEvent>of(eventMetadata);
  }


  public ModelsEventDeliveryResponse eventType(@jakarta.annotation.Nullable String eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * Get eventType
   * @return eventType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEventType() {
    return eventType;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventType(@jakarta.annotation.Nullable String eventType) {
    this.eventType = eventType;
  }


  public ModelsEventDeliveryResponse headers(@jakarta.annotation.Nullable Map<String, List<String>> headers) {
    this.headers = JsonNullable.<Map<String, List<String>>>of(headers);
    return this;
  }

  public ModelsEventDeliveryResponse putHeadersItem(String key, List<String> headersItem) {
    if (this.headers == null || !this.headers.isPresent() || this.headers.get() == null) {
      this.headers = JsonNullable.<Map<String, List<String>>>of(new HashMap<>());
    }
    try {
      this.headers.get().put(key, headersItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get headers
   * @return headers
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Map<String, List<String>> getHeaders() {
        return headers.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, List<String>>> getHeaders_JsonNullable() {
    return headers;
  }
  
  @JsonProperty(JSON_PROPERTY_HEADERS)
  public void setHeaders_JsonNullable(JsonNullable<Map<String, List<String>>> headers) {
    this.headers = headers;
  }

  public void setHeaders(@jakarta.annotation.Nullable Map<String, List<String>> headers) {
    this.headers = JsonNullable.<Map<String, List<String>>>of(headers);
  }


  public ModelsEventDeliveryResponse idempotencyKey(@jakarta.annotation.Nullable String idempotencyKey) {
    this.idempotencyKey = idempotencyKey;
    return this;
  }

  /**
   * Get idempotencyKey
   * @return idempotencyKey
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IDEMPOTENCY_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIdempotencyKey() {
    return idempotencyKey;
  }


  @JsonProperty(value = JSON_PROPERTY_IDEMPOTENCY_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdempotencyKey(@jakarta.annotation.Nullable String idempotencyKey) {
    this.idempotencyKey = idempotencyKey;
  }


  public ModelsEventDeliveryResponse latency(@jakarta.annotation.Nullable String latency) {
    this.latency = latency;
    return this;
  }

  /**
   * Deprecated: Latency is deprecated.
   * @return latency
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLatency() {
    return latency;
  }


  @JsonProperty(value = JSON_PROPERTY_LATENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatency(@jakarta.annotation.Nullable String latency) {
    this.latency = latency;
  }


  public ModelsEventDeliveryResponse latencySeconds(@jakarta.annotation.Nullable BigDecimal latencySeconds) {
    this.latencySeconds = latencySeconds;
    return this;
  }

  /**
   * Get latencySeconds
   * @return latencySeconds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATENCY_SECONDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getLatencySeconds() {
    return latencySeconds;
  }


  @JsonProperty(value = JSON_PROPERTY_LATENCY_SECONDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatencySeconds(@jakarta.annotation.Nullable BigDecimal latencySeconds) {
    this.latencySeconds = latencySeconds;
  }


  public ModelsEventDeliveryResponse metadata(@jakarta.annotation.Nullable DatastoreMetadata metadata) {
    this.metadata = JsonNullable.<DatastoreMetadata>of(metadata);
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public DatastoreMetadata getMetadata() {
        return metadata.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<DatastoreMetadata> getMetadata_JsonNullable() {
    return metadata;
  }
  
  @JsonProperty(JSON_PROPERTY_METADATA)
  public void setMetadata_JsonNullable(JsonNullable<DatastoreMetadata> metadata) {
    this.metadata = metadata;
  }

  public void setMetadata(@jakarta.annotation.Nullable DatastoreMetadata metadata) {
    this.metadata = JsonNullable.<DatastoreMetadata>of(metadata);
  }


  public ModelsEventDeliveryResponse projectId(@jakarta.annotation.Nullable String projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@jakarta.annotation.Nullable String projectId) {
    this.projectId = projectId;
  }


  public ModelsEventDeliveryResponse sourceMetadata(@jakarta.annotation.Nullable DatastoreSource sourceMetadata) {
    this.sourceMetadata = JsonNullable.<DatastoreSource>of(sourceMetadata);
    return this;
  }

  /**
   * Get sourceMetadata
   * @return sourceMetadata
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public DatastoreSource getSourceMetadata() {
        return sourceMetadata.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SOURCE_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<DatastoreSource> getSourceMetadata_JsonNullable() {
    return sourceMetadata;
  }
  
  @JsonProperty(JSON_PROPERTY_SOURCE_METADATA)
  public void setSourceMetadata_JsonNullable(JsonNullable<DatastoreSource> sourceMetadata) {
    this.sourceMetadata = sourceMetadata;
  }

  public void setSourceMetadata(@jakarta.annotation.Nullable DatastoreSource sourceMetadata) {
    this.sourceMetadata = JsonNullable.<DatastoreSource>of(sourceMetadata);
  }


  public ModelsEventDeliveryResponse status(@jakarta.annotation.Nullable DatastoreEventDeliveryStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DatastoreEventDeliveryStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable DatastoreEventDeliveryStatus status) {
    this.status = status;
  }


  public ModelsEventDeliveryResponse subscriptionId(@jakarta.annotation.Nullable String subscriptionId) {
    this.subscriptionId = subscriptionId;
    return this;
  }

  /**
   * Get subscriptionId
   * @return subscriptionId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBSCRIPTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSubscriptionId() {
    return subscriptionId;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBSCRIPTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubscriptionId(@jakarta.annotation.Nullable String subscriptionId) {
    this.subscriptionId = subscriptionId;
  }


  public ModelsEventDeliveryResponse targetUrl(@jakarta.annotation.Nullable String targetUrl) {
    this.targetUrl = targetUrl;
    return this;
  }

  /**
   * Get targetUrl
   * @return targetUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TARGET_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTargetUrl() {
    return targetUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_TARGET_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetUrl(@jakarta.annotation.Nullable String targetUrl) {
    this.targetUrl = targetUrl;
  }


  public ModelsEventDeliveryResponse uid(@jakarta.annotation.Nullable String uid) {
    this.uid = uid;
    return this;
  }

  /**
   * Get uid
   * @return uid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUid() {
    return uid;
  }


  @JsonProperty(value = JSON_PROPERTY_UID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUid(@jakarta.annotation.Nullable String uid) {
    this.uid = uid;
  }


  public ModelsEventDeliveryResponse updatedAt(@jakarta.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ModelsEventDeliveryResponse urlQueryParams(@jakarta.annotation.Nullable String urlQueryParams) {
    this.urlQueryParams = urlQueryParams;
    return this;
  }

  /**
   * Get urlQueryParams
   * @return urlQueryParams
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL_QUERY_PARAMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUrlQueryParams() {
    return urlQueryParams;
  }


  @JsonProperty(value = JSON_PROPERTY_URL_QUERY_PARAMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrlQueryParams(@jakarta.annotation.Nullable String urlQueryParams) {
    this.urlQueryParams = urlQueryParams;
  }


  /**
   * Return true if this models.EventDeliveryResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsEventDeliveryResponse modelsEventDeliveryResponse = (ModelsEventDeliveryResponse) o;
    return equalsNullable(this.acknowledgedAt, modelsEventDeliveryResponse.acknowledgedAt) &&
        equalsNullable(this.cliMetadata, modelsEventDeliveryResponse.cliMetadata) &&
        Objects.equals(this.createdAt, modelsEventDeliveryResponse.createdAt) &&
        equalsNullable(this.deletedAt, modelsEventDeliveryResponse.deletedAt) &&
        Objects.equals(this.deliveryMode, modelsEventDeliveryResponse.deliveryMode) &&
        Objects.equals(this.description, modelsEventDeliveryResponse.description) &&
        Objects.equals(this.deviceId, modelsEventDeliveryResponse.deviceId) &&
        equalsNullable(this.deviceMetadata, modelsEventDeliveryResponse.deviceMetadata) &&
        Objects.equals(this.endpointId, modelsEventDeliveryResponse.endpointId) &&
        equalsNullable(this.endpointMetadata, modelsEventDeliveryResponse.endpointMetadata) &&
        Objects.equals(this.eventId, modelsEventDeliveryResponse.eventId) &&
        equalsNullable(this.eventMetadata, modelsEventDeliveryResponse.eventMetadata) &&
        Objects.equals(this.eventType, modelsEventDeliveryResponse.eventType) &&
        equalsNullable(this.headers, modelsEventDeliveryResponse.headers) &&
        Objects.equals(this.idempotencyKey, modelsEventDeliveryResponse.idempotencyKey) &&
        Objects.equals(this.latency, modelsEventDeliveryResponse.latency) &&
        Objects.equals(this.latencySeconds, modelsEventDeliveryResponse.latencySeconds) &&
        equalsNullable(this.metadata, modelsEventDeliveryResponse.metadata) &&
        Objects.equals(this.projectId, modelsEventDeliveryResponse.projectId) &&
        equalsNullable(this.sourceMetadata, modelsEventDeliveryResponse.sourceMetadata) &&
        Objects.equals(this.status, modelsEventDeliveryResponse.status) &&
        Objects.equals(this.subscriptionId, modelsEventDeliveryResponse.subscriptionId) &&
        Objects.equals(this.targetUrl, modelsEventDeliveryResponse.targetUrl) &&
        Objects.equals(this.uid, modelsEventDeliveryResponse.uid) &&
        Objects.equals(this.updatedAt, modelsEventDeliveryResponse.updatedAt) &&
        Objects.equals(this.urlQueryParams, modelsEventDeliveryResponse.urlQueryParams);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(acknowledgedAt), hashCodeNullable(cliMetadata), createdAt, hashCodeNullable(deletedAt), deliveryMode, description, deviceId, hashCodeNullable(deviceMetadata), endpointId, hashCodeNullable(endpointMetadata), eventId, hashCodeNullable(eventMetadata), eventType, hashCodeNullable(headers), idempotencyKey, latency, latencySeconds, hashCodeNullable(metadata), projectId, hashCodeNullable(sourceMetadata), status, subscriptionId, targetUrl, uid, updatedAt, urlQueryParams);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsEventDeliveryResponse {\n");
    sb.append("    acknowledgedAt: ").append(toIndentedString(acknowledgedAt)).append("\n");
    sb.append("    cliMetadata: ").append(toIndentedString(cliMetadata)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deliveryMode: ").append(toIndentedString(deliveryMode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    deviceMetadata: ").append(toIndentedString(deviceMetadata)).append("\n");
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("    endpointMetadata: ").append(toIndentedString(endpointMetadata)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    eventMetadata: ").append(toIndentedString(eventMetadata)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    idempotencyKey: ").append(toIndentedString(idempotencyKey)).append("\n");
    sb.append("    latency: ").append(toIndentedString(latency)).append("\n");
    sb.append("    latencySeconds: ").append(toIndentedString(latencySeconds)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    sourceMetadata: ").append(toIndentedString(sourceMetadata)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    subscriptionId: ").append(toIndentedString(subscriptionId)).append("\n");
    sb.append("    targetUrl: ").append(toIndentedString(targetUrl)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    urlQueryParams: ").append(toIndentedString(urlQueryParams)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `acknowledged_at` to the URL query string
    if (getAcknowledgedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sacknowledged_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAcknowledgedAt()))));
    }

    // add `cli_metadata` to the URL query string
    if (getCliMetadata() != null) {
      joiner.add(getCliMetadata().toUrlQueryString(prefix + "cli_metadata" + suffix));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `deleted_at` to the URL query string
    if (getDeletedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeleted_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeletedAt()))));
    }

    // add `delivery_mode` to the URL query string
    if (getDeliveryMode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdelivery_mode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeliveryMode()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `device_id` to the URL query string
    if (getDeviceId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdevice_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeviceId()))));
    }

    // add `device_metadata` to the URL query string
    if (getDeviceMetadata() != null) {
      joiner.add(getDeviceMetadata().toUrlQueryString(prefix + "device_metadata" + suffix));
    }

    // add `endpoint_id` to the URL query string
    if (getEndpointId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sendpoint_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndpointId()))));
    }

    // add `endpoint_metadata` to the URL query string
    if (getEndpointMetadata() != null) {
      joiner.add(getEndpointMetadata().toUrlQueryString(prefix + "endpoint_metadata" + suffix));
    }

    // add `event_id` to the URL query string
    if (getEventId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sevent_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventId()))));
    }

    // add `event_metadata` to the URL query string
    if (getEventMetadata() != null) {
      joiner.add(getEventMetadata().toUrlQueryString(prefix + "event_metadata" + suffix));
    }

    // add `event_type` to the URL query string
    if (getEventType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sevent_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventType()))));
    }

    // add `headers` to the URL query string
    if (getHeaders() != null) {
      for (String _key : getHeaders().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sheaders%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getHeaders().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getHeaders().get(_key)))));
      }
    }

    // add `idempotency_key` to the URL query string
    if (getIdempotencyKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sidempotency_key%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIdempotencyKey()))));
    }

    // add `latency` to the URL query string
    if (getLatency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slatency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLatency()))));
    }

    // add `latency_seconds` to the URL query string
    if (getLatencySeconds() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slatency_seconds%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLatencySeconds()))));
    }

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      joiner.add(getMetadata().toUrlQueryString(prefix + "metadata" + suffix));
    }

    // add `project_id` to the URL query string
    if (getProjectId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectId()))));
    }

    // add `source_metadata` to the URL query string
    if (getSourceMetadata() != null) {
      joiner.add(getSourceMetadata().toUrlQueryString(prefix + "source_metadata" + suffix));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `subscription_id` to the URL query string
    if (getSubscriptionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubscription_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubscriptionId()))));
    }

    // add `target_url` to the URL query string
    if (getTargetUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%starget_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTargetUrl()))));
    }

    // add `uid` to the URL query string
    if (getUid() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUid()))));
    }

    // add `updated_at` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    // add `url_query_params` to the URL query string
    if (getUrlQueryParams() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%surl_query_params%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrlQueryParams()))));
    }

    return joiner.toString();
  }
}

