/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.getconvoy.models.ModelsAmqpAuth;
import com.getconvoy.models.ModelsAmqpExchange;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * ModelsAmqpPubSubconfig
 */
@JsonPropertyOrder({
  ModelsAmqpPubSubconfig.JSON_PROPERTY_HOST,
  ModelsAmqpPubSubconfig.JSON_PROPERTY_AUTH,
  ModelsAmqpPubSubconfig.JSON_PROPERTY_BIND_EXCHANGE,
  ModelsAmqpPubSubconfig.JSON_PROPERTY_DEAD_LETTER_EXCHANGE,
  ModelsAmqpPubSubconfig.JSON_PROPERTY_PORT,
  ModelsAmqpPubSubconfig.JSON_PROPERTY_QUEUE,
  ModelsAmqpPubSubconfig.JSON_PROPERTY_SCHEMA,
  ModelsAmqpPubSubconfig.JSON_PROPERTY_VHOST
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ModelsAmqpPubSubconfig {
  public static final String JSON_PROPERTY_HOST = "host";
  @jakarta.annotation.Nullable
  private String host;

  public static final String JSON_PROPERTY_AUTH = "auth";
  @jakarta.annotation.Nullable
  private ModelsAmqpAuth auth;

  public static final String JSON_PROPERTY_BIND_EXCHANGE = "bindExchange";
  @jakarta.annotation.Nullable
  private ModelsAmqpExchange bindExchange;

  public static final String JSON_PROPERTY_DEAD_LETTER_EXCHANGE = "deadLetterExchange";
  @jakarta.annotation.Nullable
  private String deadLetterExchange;

  public static final String JSON_PROPERTY_PORT = "port";
  @jakarta.annotation.Nullable
  private String port;

  public static final String JSON_PROPERTY_QUEUE = "queue";
  @jakarta.annotation.Nullable
  private String queue;

  public static final String JSON_PROPERTY_SCHEMA = "schema";
  @jakarta.annotation.Nullable
  private String schema;

  public static final String JSON_PROPERTY_VHOST = "vhost";
  @jakarta.annotation.Nullable
  private String vhost;

  public ModelsAmqpPubSubconfig() { 
  }

  public ModelsAmqpPubSubconfig host(@jakarta.annotation.Nullable String host) {
    this.host = host;
    return this;
  }

  /**
   * Get host
   * @return host
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HOST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHost() {
    return host;
  }


  @JsonProperty(value = JSON_PROPERTY_HOST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHost(@jakarta.annotation.Nullable String host) {
    this.host = host;
  }


  public ModelsAmqpPubSubconfig auth(@jakarta.annotation.Nullable ModelsAmqpAuth auth) {
    this.auth = auth;
    return this;
  }

  /**
   * Get auth
   * @return auth
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ModelsAmqpAuth getAuth() {
    return auth;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuth(@jakarta.annotation.Nullable ModelsAmqpAuth auth) {
    this.auth = auth;
  }


  public ModelsAmqpPubSubconfig bindExchange(@jakarta.annotation.Nullable ModelsAmqpExchange bindExchange) {
    this.bindExchange = bindExchange;
    return this;
  }

  /**
   * Get bindExchange
   * @return bindExchange
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BIND_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ModelsAmqpExchange getBindExchange() {
    return bindExchange;
  }


  @JsonProperty(value = JSON_PROPERTY_BIND_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBindExchange(@jakarta.annotation.Nullable ModelsAmqpExchange bindExchange) {
    this.bindExchange = bindExchange;
  }


  public ModelsAmqpPubSubconfig deadLetterExchange(@jakarta.annotation.Nullable String deadLetterExchange) {
    this.deadLetterExchange = deadLetterExchange;
    return this;
  }

  /**
   * Get deadLetterExchange
   * @return deadLetterExchange
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEAD_LETTER_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDeadLetterExchange() {
    return deadLetterExchange;
  }


  @JsonProperty(value = JSON_PROPERTY_DEAD_LETTER_EXCHANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeadLetterExchange(@jakarta.annotation.Nullable String deadLetterExchange) {
    this.deadLetterExchange = deadLetterExchange;
  }


  public ModelsAmqpPubSubconfig port(@jakarta.annotation.Nullable String port) {
    this.port = port;
    return this;
  }

  /**
   * Get port
   * @return port
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPort() {
    return port;
  }


  @JsonProperty(value = JSON_PROPERTY_PORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPort(@jakarta.annotation.Nullable String port) {
    this.port = port;
  }


  public ModelsAmqpPubSubconfig queue(@jakarta.annotation.Nullable String queue) {
    this.queue = queue;
    return this;
  }

  /**
   * Get queue
   * @return queue
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUEUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getQueue() {
    return queue;
  }


  @JsonProperty(value = JSON_PROPERTY_QUEUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueue(@jakarta.annotation.Nullable String queue) {
    this.queue = queue;
  }


  public ModelsAmqpPubSubconfig schema(@jakarta.annotation.Nullable String schema) {
    this.schema = schema;
    return this;
  }

  /**
   * Get schema
   * @return schema
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEMA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSchema() {
    return schema;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEMA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchema(@jakarta.annotation.Nullable String schema) {
    this.schema = schema;
  }


  public ModelsAmqpPubSubconfig vhost(@jakarta.annotation.Nullable String vhost) {
    this.vhost = vhost;
    return this;
  }

  /**
   * Get vhost
   * @return vhost
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VHOST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getVhost() {
    return vhost;
  }


  @JsonProperty(value = JSON_PROPERTY_VHOST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVhost(@jakarta.annotation.Nullable String vhost) {
    this.vhost = vhost;
  }


  /**
   * Return true if this models.AmqpPubSubconfig object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsAmqpPubSubconfig modelsAmqpPubSubconfig = (ModelsAmqpPubSubconfig) o;
    return Objects.equals(this.host, modelsAmqpPubSubconfig.host) &&
        Objects.equals(this.auth, modelsAmqpPubSubconfig.auth) &&
        Objects.equals(this.bindExchange, modelsAmqpPubSubconfig.bindExchange) &&
        Objects.equals(this.deadLetterExchange, modelsAmqpPubSubconfig.deadLetterExchange) &&
        Objects.equals(this.port, modelsAmqpPubSubconfig.port) &&
        Objects.equals(this.queue, modelsAmqpPubSubconfig.queue) &&
        Objects.equals(this.schema, modelsAmqpPubSubconfig.schema) &&
        Objects.equals(this.vhost, modelsAmqpPubSubconfig.vhost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(host, auth, bindExchange, deadLetterExchange, port, queue, schema, vhost);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsAmqpPubSubconfig {\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    auth: ").append(toIndentedString(auth)).append("\n");
    sb.append("    bindExchange: ").append(toIndentedString(bindExchange)).append("\n");
    sb.append("    deadLetterExchange: ").append(toIndentedString(deadLetterExchange)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    queue: ").append(toIndentedString(queue)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    vhost: ").append(toIndentedString(vhost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `host` to the URL query string
    if (getHost() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shost%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHost()))));
    }

    // add `auth` to the URL query string
    if (getAuth() != null) {
      joiner.add(getAuth().toUrlQueryString(prefix + "auth" + suffix));
    }

    // add `bindExchange` to the URL query string
    if (getBindExchange() != null) {
      joiner.add(getBindExchange().toUrlQueryString(prefix + "bindExchange" + suffix));
    }

    // add `deadLetterExchange` to the URL query string
    if (getDeadLetterExchange() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeadLetterExchange%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeadLetterExchange()))));
    }

    // add `port` to the URL query string
    if (getPort() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sport%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPort()))));
    }

    // add `queue` to the URL query string
    if (getQueue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squeue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQueue()))));
    }

    // add `schema` to the URL query string
    if (getSchema() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sschema%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSchema()))));
    }

    // add `vhost` to the URL query string
    if (getVhost() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svhost%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVhost()))));
    }

    return joiner.toString();
  }
}

