/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * ModelsFilterResponse
 */
@JsonPropertyOrder({
  ModelsFilterResponse.JSON_PROPERTY_BODY,
  ModelsFilterResponse.JSON_PROPERTY_ENABLED_AT,
  ModelsFilterResponse.JSON_PROPERTY_EVENT_TYPE,
  ModelsFilterResponse.JSON_PROPERTY_HEADERS,
  ModelsFilterResponse.JSON_PROPERTY_PATH,
  ModelsFilterResponse.JSON_PROPERTY_QUERY,
  ModelsFilterResponse.JSON_PROPERTY_RAW_BODY,
  ModelsFilterResponse.JSON_PROPERTY_RAW_HEADERS,
  ModelsFilterResponse.JSON_PROPERTY_RAW_PATH,
  ModelsFilterResponse.JSON_PROPERTY_RAW_QUERY,
  ModelsFilterResponse.JSON_PROPERTY_SUBSCRIPTION_ID,
  ModelsFilterResponse.JSON_PROPERTY_UID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ModelsFilterResponse {
  public static final String JSON_PROPERTY_BODY = "body";
  private JsonNullable<Map<String, Object>> body = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_ENABLED_AT = "enabled_at";
  private JsonNullable<String> enabledAt = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_EVENT_TYPE = "event_type";
  @jakarta.annotation.Nullable
  private String eventType;

  public static final String JSON_PROPERTY_HEADERS = "headers";
  private JsonNullable<Map<String, Object>> headers = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_PATH = "path";
  private JsonNullable<Map<String, Object>> path = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_QUERY = "query";
  private JsonNullable<Map<String, Object>> query = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_RAW_BODY = "raw_body";
  private JsonNullable<Map<String, Object>> rawBody = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_RAW_HEADERS = "raw_headers";
  private JsonNullable<Map<String, Object>> rawHeaders = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_RAW_PATH = "raw_path";
  private JsonNullable<Map<String, Object>> rawPath = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_RAW_QUERY = "raw_query";
  private JsonNullable<Map<String, Object>> rawQuery = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_SUBSCRIPTION_ID = "subscription_id";
  @jakarta.annotation.Nullable
  private String subscriptionId;

  public static final String JSON_PROPERTY_UID = "uid";
  @jakarta.annotation.Nullable
  private String uid;

  public ModelsFilterResponse() { 
  }

  public ModelsFilterResponse body(@jakarta.annotation.Nullable Map<String, Object> body) {
    this.body = JsonNullable.<Map<String, Object>>of(body);
    return this;
  }

  public ModelsFilterResponse putBodyItem(String key, Object bodyItem) {
    if (this.body == null || !this.body.isPresent()) {
      this.body = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.body.get().put(key, bodyItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get body
   * @return body
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Map<String, Object> getBody() {
        return body.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getBody_JsonNullable() {
    return body;
  }
  
  @JsonProperty(JSON_PROPERTY_BODY)
  public void setBody_JsonNullable(JsonNullable<Map<String, Object>> body) {
    this.body = body;
  }

  public void setBody(@jakarta.annotation.Nullable Map<String, Object> body) {
    this.body = JsonNullable.<Map<String, Object>>of(body);
  }


  public ModelsFilterResponse enabledAt(@jakarta.annotation.Nullable String enabledAt) {
    this.enabledAt = JsonNullable.<String>of(enabledAt);
    return this;
  }

  /**
   * Get enabledAt
   * @return enabledAt
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getEnabledAt() {
        return enabledAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ENABLED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getEnabledAt_JsonNullable() {
    return enabledAt;
  }
  
  @JsonProperty(JSON_PROPERTY_ENABLED_AT)
  public void setEnabledAt_JsonNullable(JsonNullable<String> enabledAt) {
    this.enabledAt = enabledAt;
  }

  public void setEnabledAt(@jakarta.annotation.Nullable String enabledAt) {
    this.enabledAt = JsonNullable.<String>of(enabledAt);
  }


  public ModelsFilterResponse eventType(@jakarta.annotation.Nullable String eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * Get eventType
   * @return eventType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEventType() {
    return eventType;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventType(@jakarta.annotation.Nullable String eventType) {
    this.eventType = eventType;
  }


  public ModelsFilterResponse headers(@jakarta.annotation.Nullable Map<String, Object> headers) {
    this.headers = JsonNullable.<Map<String, Object>>of(headers);
    return this;
  }

  public ModelsFilterResponse putHeadersItem(String key, Object headersItem) {
    if (this.headers == null || !this.headers.isPresent()) {
      this.headers = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.headers.get().put(key, headersItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get headers
   * @return headers
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Map<String, Object> getHeaders() {
        return headers.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getHeaders_JsonNullable() {
    return headers;
  }
  
  @JsonProperty(JSON_PROPERTY_HEADERS)
  public void setHeaders_JsonNullable(JsonNullable<Map<String, Object>> headers) {
    this.headers = headers;
  }

  public void setHeaders(@jakarta.annotation.Nullable Map<String, Object> headers) {
    this.headers = JsonNullable.<Map<String, Object>>of(headers);
  }


  public ModelsFilterResponse path(@jakarta.annotation.Nullable Map<String, Object> path) {
    this.path = JsonNullable.<Map<String, Object>>of(path);
    return this;
  }

  public ModelsFilterResponse putPathItem(String key, Object pathItem) {
    if (this.path == null || !this.path.isPresent()) {
      this.path = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.path.get().put(key, pathItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get path
   * @return path
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Map<String, Object> getPath() {
        return path.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getPath_JsonNullable() {
    return path;
  }
  
  @JsonProperty(JSON_PROPERTY_PATH)
  public void setPath_JsonNullable(JsonNullable<Map<String, Object>> path) {
    this.path = path;
  }

  public void setPath(@jakarta.annotation.Nullable Map<String, Object> path) {
    this.path = JsonNullable.<Map<String, Object>>of(path);
  }


  public ModelsFilterResponse query(@jakarta.annotation.Nullable Map<String, Object> query) {
    this.query = JsonNullable.<Map<String, Object>>of(query);
    return this;
  }

  public ModelsFilterResponse putQueryItem(String key, Object queryItem) {
    if (this.query == null || !this.query.isPresent()) {
      this.query = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.query.get().put(key, queryItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get query
   * @return query
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Map<String, Object> getQuery() {
        return query.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_QUERY, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getQuery_JsonNullable() {
    return query;
  }
  
  @JsonProperty(JSON_PROPERTY_QUERY)
  public void setQuery_JsonNullable(JsonNullable<Map<String, Object>> query) {
    this.query = query;
  }

  public void setQuery(@jakarta.annotation.Nullable Map<String, Object> query) {
    this.query = JsonNullable.<Map<String, Object>>of(query);
  }


  public ModelsFilterResponse rawBody(@jakarta.annotation.Nullable Map<String, Object> rawBody) {
    this.rawBody = JsonNullable.<Map<String, Object>>of(rawBody);
    return this;
  }

  public ModelsFilterResponse putRawBodyItem(String key, Object rawBodyItem) {
    if (this.rawBody == null || !this.rawBody.isPresent()) {
      this.rawBody = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.rawBody.get().put(key, rawBodyItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get rawBody
   * @return rawBody
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Map<String, Object> getRawBody() {
        return rawBody.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_RAW_BODY, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getRawBody_JsonNullable() {
    return rawBody;
  }
  
  @JsonProperty(JSON_PROPERTY_RAW_BODY)
  public void setRawBody_JsonNullable(JsonNullable<Map<String, Object>> rawBody) {
    this.rawBody = rawBody;
  }

  public void setRawBody(@jakarta.annotation.Nullable Map<String, Object> rawBody) {
    this.rawBody = JsonNullable.<Map<String, Object>>of(rawBody);
  }


  public ModelsFilterResponse rawHeaders(@jakarta.annotation.Nullable Map<String, Object> rawHeaders) {
    this.rawHeaders = JsonNullable.<Map<String, Object>>of(rawHeaders);
    return this;
  }

  public ModelsFilterResponse putRawHeadersItem(String key, Object rawHeadersItem) {
    if (this.rawHeaders == null || !this.rawHeaders.isPresent()) {
      this.rawHeaders = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.rawHeaders.get().put(key, rawHeadersItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get rawHeaders
   * @return rawHeaders
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Map<String, Object> getRawHeaders() {
        return rawHeaders.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_RAW_HEADERS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getRawHeaders_JsonNullable() {
    return rawHeaders;
  }
  
  @JsonProperty(JSON_PROPERTY_RAW_HEADERS)
  public void setRawHeaders_JsonNullable(JsonNullable<Map<String, Object>> rawHeaders) {
    this.rawHeaders = rawHeaders;
  }

  public void setRawHeaders(@jakarta.annotation.Nullable Map<String, Object> rawHeaders) {
    this.rawHeaders = JsonNullable.<Map<String, Object>>of(rawHeaders);
  }


  public ModelsFilterResponse rawPath(@jakarta.annotation.Nullable Map<String, Object> rawPath) {
    this.rawPath = JsonNullable.<Map<String, Object>>of(rawPath);
    return this;
  }

  public ModelsFilterResponse putRawPathItem(String key, Object rawPathItem) {
    if (this.rawPath == null || !this.rawPath.isPresent()) {
      this.rawPath = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.rawPath.get().put(key, rawPathItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get rawPath
   * @return rawPath
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Map<String, Object> getRawPath() {
        return rawPath.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_RAW_PATH, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getRawPath_JsonNullable() {
    return rawPath;
  }
  
  @JsonProperty(JSON_PROPERTY_RAW_PATH)
  public void setRawPath_JsonNullable(JsonNullable<Map<String, Object>> rawPath) {
    this.rawPath = rawPath;
  }

  public void setRawPath(@jakarta.annotation.Nullable Map<String, Object> rawPath) {
    this.rawPath = JsonNullable.<Map<String, Object>>of(rawPath);
  }


  public ModelsFilterResponse rawQuery(@jakarta.annotation.Nullable Map<String, Object> rawQuery) {
    this.rawQuery = JsonNullable.<Map<String, Object>>of(rawQuery);
    return this;
  }

  public ModelsFilterResponse putRawQueryItem(String key, Object rawQueryItem) {
    if (this.rawQuery == null || !this.rawQuery.isPresent()) {
      this.rawQuery = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.rawQuery.get().put(key, rawQueryItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get rawQuery
   * @return rawQuery
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Map<String, Object> getRawQuery() {
        return rawQuery.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_RAW_QUERY, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getRawQuery_JsonNullable() {
    return rawQuery;
  }
  
  @JsonProperty(JSON_PROPERTY_RAW_QUERY)
  public void setRawQuery_JsonNullable(JsonNullable<Map<String, Object>> rawQuery) {
    this.rawQuery = rawQuery;
  }

  public void setRawQuery(@jakarta.annotation.Nullable Map<String, Object> rawQuery) {
    this.rawQuery = JsonNullable.<Map<String, Object>>of(rawQuery);
  }


  public ModelsFilterResponse subscriptionId(@jakarta.annotation.Nullable String subscriptionId) {
    this.subscriptionId = subscriptionId;
    return this;
  }

  /**
   * Get subscriptionId
   * @return subscriptionId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBSCRIPTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSubscriptionId() {
    return subscriptionId;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBSCRIPTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubscriptionId(@jakarta.annotation.Nullable String subscriptionId) {
    this.subscriptionId = subscriptionId;
  }


  public ModelsFilterResponse uid(@jakarta.annotation.Nullable String uid) {
    this.uid = uid;
    return this;
  }

  /**
   * Get uid
   * @return uid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUid() {
    return uid;
  }


  @JsonProperty(value = JSON_PROPERTY_UID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUid(@jakarta.annotation.Nullable String uid) {
    this.uid = uid;
  }


  /**
   * Return true if this models.FilterResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsFilterResponse modelsFilterResponse = (ModelsFilterResponse) o;
    return equalsNullable(this.body, modelsFilterResponse.body) &&
        equalsNullable(this.enabledAt, modelsFilterResponse.enabledAt) &&
        Objects.equals(this.eventType, modelsFilterResponse.eventType) &&
        equalsNullable(this.headers, modelsFilterResponse.headers) &&
        equalsNullable(this.path, modelsFilterResponse.path) &&
        equalsNullable(this.query, modelsFilterResponse.query) &&
        equalsNullable(this.rawBody, modelsFilterResponse.rawBody) &&
        equalsNullable(this.rawHeaders, modelsFilterResponse.rawHeaders) &&
        equalsNullable(this.rawPath, modelsFilterResponse.rawPath) &&
        equalsNullable(this.rawQuery, modelsFilterResponse.rawQuery) &&
        Objects.equals(this.subscriptionId, modelsFilterResponse.subscriptionId) &&
        Objects.equals(this.uid, modelsFilterResponse.uid);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(body), hashCodeNullable(enabledAt), eventType, hashCodeNullable(headers), hashCodeNullable(path), hashCodeNullable(query), hashCodeNullable(rawBody), hashCodeNullable(rawHeaders), hashCodeNullable(rawPath), hashCodeNullable(rawQuery), subscriptionId, uid);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsFilterResponse {\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    enabledAt: ").append(toIndentedString(enabledAt)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    rawBody: ").append(toIndentedString(rawBody)).append("\n");
    sb.append("    rawHeaders: ").append(toIndentedString(rawHeaders)).append("\n");
    sb.append("    rawPath: ").append(toIndentedString(rawPath)).append("\n");
    sb.append("    rawQuery: ").append(toIndentedString(rawQuery)).append("\n");
    sb.append("    subscriptionId: ").append(toIndentedString(subscriptionId)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `body` to the URL query string
    if (getBody() != null) {
      for (String _key : getBody().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sbody%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getBody().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getBody().get(_key)))));
      }
    }

    // add `enabled_at` to the URL query string
    if (getEnabledAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%senabled_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnabledAt()))));
    }

    // add `event_type` to the URL query string
    if (getEventType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sevent_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventType()))));
    }

    // add `headers` to the URL query string
    if (getHeaders() != null) {
      for (String _key : getHeaders().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sheaders%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getHeaders().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getHeaders().get(_key)))));
      }
    }

    // add `path` to the URL query string
    if (getPath() != null) {
      for (String _key : getPath().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%spath%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getPath().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getPath().get(_key)))));
      }
    }

    // add `query` to the URL query string
    if (getQuery() != null) {
      for (String _key : getQuery().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%squery%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getQuery().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getQuery().get(_key)))));
      }
    }

    // add `raw_body` to the URL query string
    if (getRawBody() != null) {
      for (String _key : getRawBody().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sraw_body%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getRawBody().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getRawBody().get(_key)))));
      }
    }

    // add `raw_headers` to the URL query string
    if (getRawHeaders() != null) {
      for (String _key : getRawHeaders().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sraw_headers%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getRawHeaders().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getRawHeaders().get(_key)))));
      }
    }

    // add `raw_path` to the URL query string
    if (getRawPath() != null) {
      for (String _key : getRawPath().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sraw_path%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getRawPath().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getRawPath().get(_key)))));
      }
    }

    // add `raw_query` to the URL query string
    if (getRawQuery() != null) {
      for (String _key : getRawQuery().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sraw_query%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getRawQuery().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getRawQuery().get(_key)))));
      }
    }

    // add `subscription_id` to the URL query string
    if (getSubscriptionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubscription_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubscriptionId()))));
    }

    // add `uid` to the URL query string
    if (getUid() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUid()))));
    }

    return joiner.toString();
  }
}

