/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * ModelsCreateEvent
 */
@JsonPropertyOrder({
  ModelsCreateEvent.JSON_PROPERTY_APP_ID,
  ModelsCreateEvent.JSON_PROPERTY_CUSTOM_HEADERS,
  ModelsCreateEvent.JSON_PROPERTY_DATA,
  ModelsCreateEvent.JSON_PROPERTY_ENDPOINT_ID,
  ModelsCreateEvent.JSON_PROPERTY_EVENT_TYPE,
  ModelsCreateEvent.JSON_PROPERTY_IDEMPOTENCY_KEY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ModelsCreateEvent {
  public static final String JSON_PROPERTY_APP_ID = "app_id";
  @jakarta.annotation.Nullable
  private String appId;

  public static final String JSON_PROPERTY_CUSTOM_HEADERS = "custom_headers";
  private JsonNullable<Map<String, String>> customHeaders = JsonNullable.<Map<String, String>>undefined();

  public static final String JSON_PROPERTY_DATA = "data";
  private JsonNullable<Map<String, Object>> data = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_ENDPOINT_ID = "endpoint_id";
  @jakarta.annotation.Nullable
  private String endpointId;

  public static final String JSON_PROPERTY_EVENT_TYPE = "event_type";
  @jakarta.annotation.Nullable
  private String eventType;

  public static final String JSON_PROPERTY_IDEMPOTENCY_KEY = "idempotency_key";
  @jakarta.annotation.Nullable
  private String idempotencyKey;

  public ModelsCreateEvent() { 
  }

  public ModelsCreateEvent appId(@jakarta.annotation.Nullable String appId) {
    this.appId = appId;
    return this;
  }

  /**
   * Deprecated but necessary for backward compatibility.
   * @return appId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APP_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAppId() {
    return appId;
  }


  @JsonProperty(value = JSON_PROPERTY_APP_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppId(@jakarta.annotation.Nullable String appId) {
    this.appId = appId;
  }


  public ModelsCreateEvent customHeaders(@jakarta.annotation.Nullable Map<String, String> customHeaders) {
    this.customHeaders = JsonNullable.<Map<String, String>>of(customHeaders);
    return this;
  }

  public ModelsCreateEvent putCustomHeadersItem(String key, String customHeadersItem) {
    if (this.customHeaders == null || !this.customHeaders.isPresent()) {
      this.customHeaders = JsonNullable.<Map<String, String>>of(new HashMap<>());
    }
    try {
      this.customHeaders.get().put(key, customHeadersItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Specifies custom headers you want convoy to add when the event is dispatched to your endpoint
   * @return customHeaders
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Map<String, String> getCustomHeaders() {
        return customHeaders.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CUSTOM_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, String>> getCustomHeaders_JsonNullable() {
    return customHeaders;
  }
  
  @JsonProperty(JSON_PROPERTY_CUSTOM_HEADERS)
  public void setCustomHeaders_JsonNullable(JsonNullable<Map<String, String>> customHeaders) {
    this.customHeaders = customHeaders;
  }

  public void setCustomHeaders(@jakarta.annotation.Nullable Map<String, String> customHeaders) {
    this.customHeaders = JsonNullable.<Map<String, String>>of(customHeaders);
  }


  public ModelsCreateEvent data(@jakarta.annotation.Nullable Map<String, Object> data) {
    this.data = JsonNullable.<Map<String, Object>>of(data);
    return this;
  }

  public ModelsCreateEvent putDataItem(String key, Object dataItem) {
    if (this.data == null || !this.data.isPresent()) {
      this.data = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.data.get().put(key, dataItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Data is an arbitrary JSON value that gets sent as the body of the webhook to the endpoints
   * @return data
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Map<String, Object> getData() {
        return data.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getData_JsonNullable() {
    return data;
  }
  
  @JsonProperty(JSON_PROPERTY_DATA)
  public void setData_JsonNullable(JsonNullable<Map<String, Object>> data) {
    this.data = data;
  }

  public void setData(@jakarta.annotation.Nullable Map<String, Object> data) {
    this.data = JsonNullable.<Map<String, Object>>of(data);
  }


  public ModelsCreateEvent endpointId(@jakarta.annotation.Nullable String endpointId) {
    this.endpointId = endpointId;
    return this;
  }

  /**
   * Specifies the endpoint to send this event to.
   * @return endpointId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEndpointId() {
    return endpointId;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpointId(@jakarta.annotation.Nullable String endpointId) {
    this.endpointId = endpointId;
  }


  public ModelsCreateEvent eventType(@jakarta.annotation.Nullable String eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * Event Type is used for filtering and debugging e.g invoice.paid
   * @return eventType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEventType() {
    return eventType;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventType(@jakarta.annotation.Nullable String eventType) {
    this.eventType = eventType;
  }


  public ModelsCreateEvent idempotencyKey(@jakarta.annotation.Nullable String idempotencyKey) {
    this.idempotencyKey = idempotencyKey;
    return this;
  }

  /**
   * Specify a key for event deduplication
   * @return idempotencyKey
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IDEMPOTENCY_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIdempotencyKey() {
    return idempotencyKey;
  }


  @JsonProperty(value = JSON_PROPERTY_IDEMPOTENCY_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdempotencyKey(@jakarta.annotation.Nullable String idempotencyKey) {
    this.idempotencyKey = idempotencyKey;
  }


  /**
   * Return true if this models.CreateEvent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsCreateEvent modelsCreateEvent = (ModelsCreateEvent) o;
    return Objects.equals(this.appId, modelsCreateEvent.appId) &&
        equalsNullable(this.customHeaders, modelsCreateEvent.customHeaders) &&
        equalsNullable(this.data, modelsCreateEvent.data) &&
        Objects.equals(this.endpointId, modelsCreateEvent.endpointId) &&
        Objects.equals(this.eventType, modelsCreateEvent.eventType) &&
        Objects.equals(this.idempotencyKey, modelsCreateEvent.idempotencyKey);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, hashCodeNullable(customHeaders), hashCodeNullable(data), endpointId, eventType, idempotencyKey);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsCreateEvent {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    customHeaders: ").append(toIndentedString(customHeaders)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    idempotencyKey: ").append(toIndentedString(idempotencyKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `app_id` to the URL query string
    if (getAppId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sapp_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAppId()))));
    }

    // add `custom_headers` to the URL query string
    if (getCustomHeaders() != null) {
      for (String _key : getCustomHeaders().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%scustom_headers%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getCustomHeaders().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getCustomHeaders().get(_key)))));
      }
    }

    // add `data` to the URL query string
    if (getData() != null) {
      for (String _key : getData().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdata%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getData().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getData().get(_key)))));
      }
    }

    // add `endpoint_id` to the URL query string
    if (getEndpointId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sendpoint_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndpointId()))));
    }

    // add `event_type` to the URL query string
    if (getEventType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sevent_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventType()))));
    }

    // add `idempotency_key` to the URL query string
    if (getIdempotencyKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sidempotency_key%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIdempotencyKey()))));
    }

    return joiner.toString();
  }
}

