/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * ModelsEventTypeResponse
 */
@JsonPropertyOrder({
  ModelsEventTypeResponse.JSON_PROPERTY_CATEGORY,
  ModelsEventTypeResponse.JSON_PROPERTY_DEPRECATED_AT,
  ModelsEventTypeResponse.JSON_PROPERTY_DESCRIPTION,
  ModelsEventTypeResponse.JSON_PROPERTY_JSON_SCHEMA,
  ModelsEventTypeResponse.JSON_PROPERTY_NAME,
  ModelsEventTypeResponse.JSON_PROPERTY_UID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ModelsEventTypeResponse {
  public static final String JSON_PROPERTY_CATEGORY = "category";
  @jakarta.annotation.Nullable
  private String category;

  public static final String JSON_PROPERTY_DEPRECATED_AT = "deprecated_at";
  @jakarta.annotation.Nullable
  private String deprecatedAt;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_JSON_SCHEMA = "json_schema";
  @jakarta.annotation.Nullable
  private Map<String, Object> jsonSchema = new HashMap<>();

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_UID = "uid";
  @jakarta.annotation.Nullable
  private String uid;

  public ModelsEventTypeResponse() { 
  }

  public ModelsEventTypeResponse category(@jakarta.annotation.Nullable String category) {
    this.category = category;
    return this;
  }

  /**
   * Get category
   * @return category
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CATEGORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCategory() {
    return category;
  }


  @JsonProperty(value = JSON_PROPERTY_CATEGORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategory(@jakarta.annotation.Nullable String category) {
    this.category = category;
  }


  public ModelsEventTypeResponse deprecatedAt(@jakarta.annotation.Nullable String deprecatedAt) {
    this.deprecatedAt = deprecatedAt;
    return this;
  }

  /**
   * Get deprecatedAt
   * @return deprecatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEPRECATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDeprecatedAt() {
    return deprecatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_DEPRECATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeprecatedAt(@jakarta.annotation.Nullable String deprecatedAt) {
    this.deprecatedAt = deprecatedAt;
  }


  public ModelsEventTypeResponse description(@jakarta.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }


  public ModelsEventTypeResponse jsonSchema(@jakarta.annotation.Nullable Map<String, Object> jsonSchema) {
    this.jsonSchema = jsonSchema;
    return this;
  }

  public ModelsEventTypeResponse putJsonSchemaItem(String key, Object jsonSchemaItem) {
    if (this.jsonSchema == null) {
      this.jsonSchema = new HashMap<>();
    }
    this.jsonSchema.put(key, jsonSchemaItem);
    return this;
  }

  /**
   * Get jsonSchema
   * @return jsonSchema
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_JSON_SCHEMA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getJsonSchema() {
    return jsonSchema;
  }


  @JsonProperty(value = JSON_PROPERTY_JSON_SCHEMA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setJsonSchema(@jakarta.annotation.Nullable Map<String, Object> jsonSchema) {
    this.jsonSchema = jsonSchema;
  }


  public ModelsEventTypeResponse name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public ModelsEventTypeResponse uid(@jakarta.annotation.Nullable String uid) {
    this.uid = uid;
    return this;
  }

  /**
   * Get uid
   * @return uid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUid() {
    return uid;
  }


  @JsonProperty(value = JSON_PROPERTY_UID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUid(@jakarta.annotation.Nullable String uid) {
    this.uid = uid;
  }


  /**
   * Return true if this models.EventTypeResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsEventTypeResponse modelsEventTypeResponse = (ModelsEventTypeResponse) o;
    return Objects.equals(this.category, modelsEventTypeResponse.category) &&
        Objects.equals(this.deprecatedAt, modelsEventTypeResponse.deprecatedAt) &&
        Objects.equals(this.description, modelsEventTypeResponse.description) &&
        Objects.equals(this.jsonSchema, modelsEventTypeResponse.jsonSchema) &&
        Objects.equals(this.name, modelsEventTypeResponse.name) &&
        Objects.equals(this.uid, modelsEventTypeResponse.uid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category, deprecatedAt, description, jsonSchema, name, uid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsEventTypeResponse {\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    deprecatedAt: ").append(toIndentedString(deprecatedAt)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    jsonSchema: ").append(toIndentedString(jsonSchema)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `category` to the URL query string
    if (getCategory() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scategory%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCategory()))));
    }

    // add `deprecated_at` to the URL query string
    if (getDeprecatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeprecated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeprecatedAt()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `json_schema` to the URL query string
    if (getJsonSchema() != null) {
      for (String _key : getJsonSchema().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sjson_schema%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getJsonSchema().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getJsonSchema().get(_key)))));
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `uid` to the URL query string
    if (getUid() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUid()))));
    }

    return joiner.toString();
  }
}

