/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.getconvoy.models.DatastoreStrategyProvider;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * ModelsRetryConfiguration
 */
@JsonPropertyOrder({
  ModelsRetryConfiguration.JSON_PROPERTY_DURATION,
  ModelsRetryConfiguration.JSON_PROPERTY_INTERVAL_SECONDS,
  ModelsRetryConfiguration.JSON_PROPERTY_RETRY_COUNT,
  ModelsRetryConfiguration.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ModelsRetryConfiguration {
  public static final String JSON_PROPERTY_DURATION = "duration";
  @jakarta.annotation.Nullable
  private String duration;

  public static final String JSON_PROPERTY_INTERVAL_SECONDS = "interval_seconds";
  @jakarta.annotation.Nullable
  private Integer intervalSeconds;

  public static final String JSON_PROPERTY_RETRY_COUNT = "retry_count";
  @jakarta.annotation.Nullable
  private Integer retryCount;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private DatastoreStrategyProvider type;

  public ModelsRetryConfiguration() { 
  }

  public ModelsRetryConfiguration duration(@jakarta.annotation.Nullable String duration) {
    this.duration = duration;
    return this;
  }

  /**
   * Used to specify a valid Go time duration e.g 10s, 1h3m for how long to wait between event delivery retries
   * @return duration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DURATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDuration() {
    return duration;
  }


  @JsonProperty(value = JSON_PROPERTY_DURATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(@jakarta.annotation.Nullable String duration) {
    this.duration = duration;
  }


  public ModelsRetryConfiguration intervalSeconds(@jakarta.annotation.Nullable Integer intervalSeconds) {
    this.intervalSeconds = intervalSeconds;
    return this;
  }

  /**
   * Used to specify a time in seconds for how long to wait between event delivery retries,
   * @return intervalSeconds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INTERVAL_SECONDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getIntervalSeconds() {
    return intervalSeconds;
  }


  @JsonProperty(value = JSON_PROPERTY_INTERVAL_SECONDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntervalSeconds(@jakarta.annotation.Nullable Integer intervalSeconds) {
    this.intervalSeconds = intervalSeconds;
  }


  public ModelsRetryConfiguration retryCount(@jakarta.annotation.Nullable Integer retryCount) {
    this.retryCount = retryCount;
    return this;
  }

  /**
   * Used to specify the max number of retries
   * @return retryCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RETRY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getRetryCount() {
    return retryCount;
  }


  @JsonProperty(value = JSON_PROPERTY_RETRY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetryCount(@jakarta.annotation.Nullable Integer retryCount) {
    this.retryCount = retryCount;
  }


  public ModelsRetryConfiguration type(@jakarta.annotation.Nullable DatastoreStrategyProvider type) {
    this.type = type;
    return this;
  }

  /**
   * Retry Strategy type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DatastoreStrategyProvider getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable DatastoreStrategyProvider type) {
    this.type = type;
  }


  /**
   * Return true if this models.RetryConfiguration object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsRetryConfiguration modelsRetryConfiguration = (ModelsRetryConfiguration) o;
    return Objects.equals(this.duration, modelsRetryConfiguration.duration) &&
        Objects.equals(this.intervalSeconds, modelsRetryConfiguration.intervalSeconds) &&
        Objects.equals(this.retryCount, modelsRetryConfiguration.retryCount) &&
        Objects.equals(this.type, modelsRetryConfiguration.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(duration, intervalSeconds, retryCount, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsRetryConfiguration {\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    intervalSeconds: ").append(toIndentedString(intervalSeconds)).append("\n");
    sb.append("    retryCount: ").append(toIndentedString(retryCount)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `duration` to the URL query string
    if (getDuration() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sduration%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDuration()))));
    }

    // add `interval_seconds` to the URL query string
    if (getIntervalSeconds() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinterval_seconds%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIntervalSeconds()))));
    }

    // add `retry_count` to the URL query string
    if (getRetryCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sretry_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRetryCount()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    return joiner.toString();
  }
}

