/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * ModelsSignatureVersion
 */
@JsonPropertyOrder({
  ModelsSignatureVersion.JSON_PROPERTY_CREATED_AT,
  ModelsSignatureVersion.JSON_PROPERTY_ENCODING,
  ModelsSignatureVersion.JSON_PROPERTY_HASH,
  ModelsSignatureVersion.JSON_PROPERTY_UID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ModelsSignatureVersion {
  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nullable
  private String createdAt;

  public static final String JSON_PROPERTY_ENCODING = "encoding";
  @jakarta.annotation.Nullable
  private String encoding;

  public static final String JSON_PROPERTY_HASH = "hash";
  @jakarta.annotation.Nullable
  private String hash;

  public static final String JSON_PROPERTY_UID = "uid";
  @jakarta.annotation.Nullable
  private String uid;

  public ModelsSignatureVersion() { 
  }

  public ModelsSignatureVersion createdAt(@jakarta.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@jakarta.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public ModelsSignatureVersion encoding(@jakarta.annotation.Nullable String encoding) {
    this.encoding = encoding;
    return this;
  }

  /**
   * Get encoding
   * @return encoding
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENCODING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEncoding() {
    return encoding;
  }


  @JsonProperty(value = JSON_PROPERTY_ENCODING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncoding(@jakarta.annotation.Nullable String encoding) {
    this.encoding = encoding;
  }


  public ModelsSignatureVersion hash(@jakarta.annotation.Nullable String hash) {
    this.hash = hash;
    return this;
  }

  /**
   * Get hash
   * @return hash
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HASH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHash() {
    return hash;
  }


  @JsonProperty(value = JSON_PROPERTY_HASH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHash(@jakarta.annotation.Nullable String hash) {
    this.hash = hash;
  }


  public ModelsSignatureVersion uid(@jakarta.annotation.Nullable String uid) {
    this.uid = uid;
    return this;
  }

  /**
   * Get uid
   * @return uid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUid() {
    return uid;
  }


  @JsonProperty(value = JSON_PROPERTY_UID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUid(@jakarta.annotation.Nullable String uid) {
    this.uid = uid;
  }


  /**
   * Return true if this models.SignatureVersion object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsSignatureVersion modelsSignatureVersion = (ModelsSignatureVersion) o;
    return Objects.equals(this.createdAt, modelsSignatureVersion.createdAt) &&
        Objects.equals(this.encoding, modelsSignatureVersion.encoding) &&
        Objects.equals(this.hash, modelsSignatureVersion.hash) &&
        Objects.equals(this.uid, modelsSignatureVersion.uid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, encoding, hash, uid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsSignatureVersion {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    encoding: ").append(toIndentedString(encoding)).append("\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `encoding` to the URL query string
    if (getEncoding() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sencoding%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEncoding()))));
    }

    // add `hash` to the URL query string
    if (getHash() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shash%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHash()))));
    }

    // add `uid` to the URL query string
    if (getUid() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUid()))));
    }

    return joiner.toString();
  }
}

