/*
 * Convoy API Reference
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.getconvoy.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.getconvoy.models.ModelsFS;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.getconvoy.client.ApiClient;
/**
 * ModelsFilterConfiguration
 */
@JsonPropertyOrder({
  ModelsFilterConfiguration.JSON_PROPERTY_EVENT_TYPES,
  ModelsFilterConfiguration.JSON_PROPERTY_FILTER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ModelsFilterConfiguration {
  public static final String JSON_PROPERTY_EVENT_TYPES = "event_types";
  @jakarta.annotation.Nullable
  private List<String> eventTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_FILTER = "filter";
  @jakarta.annotation.Nullable
  private ModelsFS filter;

  public ModelsFilterConfiguration() { 
  }

  public ModelsFilterConfiguration eventTypes(@jakarta.annotation.Nullable List<String> eventTypes) {
    this.eventTypes = eventTypes;
    return this;
  }

  public ModelsFilterConfiguration addEventTypesItem(String eventTypesItem) {
    if (this.eventTypes == null) {
      this.eventTypes = new ArrayList<>();
    }
    this.eventTypes.add(eventTypesItem);
    return this;
  }

  /**
   * List of event types that the subscription should match
   * @return eventTypes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getEventTypes() {
    return eventTypes;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventTypes(@jakarta.annotation.Nullable List<String> eventTypes) {
    this.eventTypes = eventTypes;
  }


  public ModelsFilterConfiguration filter(@jakarta.annotation.Nullable ModelsFS filter) {
    this.filter = filter;
    return this;
  }

  /**
   * Body &amp; Header filters
   * @return filter
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ModelsFS getFilter() {
    return filter;
  }


  @JsonProperty(value = JSON_PROPERTY_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilter(@jakarta.annotation.Nullable ModelsFS filter) {
    this.filter = filter;
  }


  /**
   * Return true if this models.FilterConfiguration object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsFilterConfiguration modelsFilterConfiguration = (ModelsFilterConfiguration) o;
    return Objects.equals(this.eventTypes, modelsFilterConfiguration.eventTypes) &&
        Objects.equals(this.filter, modelsFilterConfiguration.filter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventTypes, filter);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsFilterConfiguration {\n");
    sb.append("    eventTypes: ").append(toIndentedString(eventTypes)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `event_types` to the URL query string
    if (getEventTypes() != null) {
      for (int i = 0; i < getEventTypes().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sevent_types%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getEventTypes().get(i)))));
      }
    }

    // add `filter` to the URL query string
    if (getFilter() != null) {
      joiner.add(getFilter().toUrlQueryString(prefix + "filter" + suffix));
    }

    return joiner.toString();
  }
}

